package org.cloudburstmc.api.block;

import java.util.*;

import static org.cloudburstmc.api.block.BlockTypes.*;

public final class BlockTags {
    public static final BlockTag BUTTON = BlockTag.of("minecraft:button");
    public static final BlockTag CROPS = BlockTag.of("minecraft:crops");
    public static final BlockTag DOOR = BlockTag.of("minecraft:door");
    public static final BlockTag DOUBLE_SLAB = BlockTag.of("minecraft:double_slab");
    public static final BlockTag FENCE = BlockTag.of("minecraft:fence");
    public static final BlockTag FENCE_GATE = BlockTag.of("minecraft:fence_gate");
    public static final BlockTag GROUND = BlockTag.of("minecraft:ground");
    public static final BlockTag LEAVES = BlockTag.of("minecraft:leaves");
    public static final BlockTag LIQUID = BlockTag.of("minecraft:liquid");
    public static final BlockTag LOG = BlockTag.of("minecraft:log");
    public static final BlockTag PLANKS = BlockTag.of("minecraft:planks");
    public static final BlockTag PRESSURE_PLATE = BlockTag.of("minecraft:pressure_plate");
    public static final BlockTag RAIL = BlockTag.of("minecraft:rail");
    public static final BlockTag SAPLING = BlockTag.of("minecraft:sapling");
    public static final BlockTag SIGN = BlockTag.of("minecraft:sign");
    public static final BlockTag SLAB = BlockTag.of("minecraft:slab");
    public static final BlockTag SOLID = BlockTag.of("minecraft:solid");
    public static final BlockTag STAIRS = BlockTag.of("minecraft:stairs");
    public static final BlockTag STEM = BlockTag.of("minecraft:stem");
    public static final BlockTag TRANSPARENT = BlockTag.of("minecraft:transparent");
    public static final BlockTag TRAPDOOR = BlockTag.of("minecraft:trapdoor");
    public static final BlockTag WALLS = BlockTag.of("minecraft:walls");
    public static final BlockTag WOOL = BlockTag.of("minecraft:wool");

    private static final Map<BlockTag, Set<BlockType>> TAG_MAP = new HashMap<>();

    static {
        initSolid();
        initTransparent();
        initStairs();
        initSlab();
        initDoubleSlab();
        initDoor();
        initTrapdoor();
        initLiquid();
        initCrops();
        initWalls();
        initSign();
        initStem();
        initButton();
        initPressurePlate();
        initRail();
        initGround();
        initFence();
        initFenceGate();
        initWool();
        initLog();
        initPlanks();
        initSapling();
        initLeaves();
        inherit(TRANSPARENT, BUTTON, CROPS, DOOR, FENCE, FENCE_GATE, LIQUID, PRESSURE_PLATE, RAIL, SIGN, SLAB, STAIRS, STEM, TRAPDOOR, WALLS);
    }

    private BlockTags() {
    }

    public static boolean hasTag(BlockType type, BlockTag tag) {
        Set<BlockType> set = TAG_MAP.get(tag);
        return set != null && set.contains(type);
    }

    public static Set<BlockType> getTypes(BlockTag tag) {
        Set<BlockType> set = TAG_MAP.get(tag);
        return set == null ? Collections.emptySet() : Collections.unmodifiableSet(set);
    }

    /**
     * Registers {@code types} under {@code tag}.
     */
    public static void tag(BlockTag tag, BlockType... types) {
        Set<BlockType> set = TAG_MAP.computeIfAbsent(tag, k -> Collections.newSetFromMap(new IdentityHashMap<>()));
        set.addAll(Arrays.asList(types));
    }

    /**
     * Copies all members of each {@code source} tag into {@code target}.
     */
    public static void inherit(BlockTag target, BlockTag... sources) {
        Set<BlockType> targetSet = TAG_MAP.computeIfAbsent(target, k -> Collections.newSetFromMap(new IdentityHashMap<>()));
        for (BlockTag source : sources) {
            Set<BlockType> sourceSet = TAG_MAP.get(source);
            if (sourceSet != null) {
                targetSet.addAll(sourceSet);
            }
        }
    }

    private static void initSolid() {
        tag(SOLID,
                ACACIA_BUTTON, ACACIA_DOOR, ACACIA_FENCE, ACACIA_FENCE_GATE, ACACIA_LEAVES, ACACIA_LOG,
                ACACIA_PLANKS, ACACIA_PRESSURE_PLATE, ACACIA_SLAB, ACACIA_STAIRS, ACACIA_STANDING_SIGN,
                ACACIA_TRAPDOOR, ACACIA_WALL_SIGN, ACACIA_WOOD, ALLOW, ANCIENT_DEBRIS, ANVIL,
                AZALEA_LEAVES, AZALEA_LEAVES_FLOWERED, BAMBOO_BUTTON, BAMBOO_DOOR, BAMBOO_FENCE,
                BAMBOO_FENCE_GATE, BAMBOO_MOSAIC, BAMBOO_MOSAIC_SLAB, BAMBOO_MOSAIC_STAIRS, BAMBOO_PLANKS,
                BAMBOO_PRESSURE_PLATE, BAMBOO_SLAB, BAMBOO_STAIRS, BAMBOO_STANDING_SIGN, BAMBOO_TRAPDOOR,
                BAMBOO_WALL_SIGN, BARREL, BARRIER, BASALT, BEACON, BED, BEDROCK, BEEHIVE, BEE_NEST, BELL,
                BIRCH_BUTTON, BIRCH_DOOR, BIRCH_FENCE, BIRCH_FENCE_GATE, BIRCH_LEAVES, BIRCH_LOG,
                BIRCH_PLANKS, BIRCH_PRESSURE_PLATE, BIRCH_SLAB, BIRCH_STAIRS, BIRCH_STANDING_SIGN,
                BIRCH_TRAPDOOR, BIRCH_WALL_SIGN, BIRCH_WOOD, BLACKSTONE, BLACK_CONCRETE,
                BLACK_CONCRETE_POWDER, BLACK_GLAZED_TERRACOTTA, BLACK_SHULKER_BOX, BLACK_STAINED_GLASS,
                BLACK_STAINED_GLASS_PANE, BLACK_TERRACOTTA, BLACK_WOOL, BLAST_FURNACE, BLUE_CONCRETE,
                BLUE_CONCRETE_POWDER, BLUE_GLAZED_TERRACOTTA, BLUE_ICE, BLUE_SHULKER_BOX,
                BLUE_STAINED_GLASS, BLUE_STAINED_GLASS_PANE, BLUE_TERRACOTTA, BLUE_WOOL, BONE_BLOCK,
                BOOKSHELF, BORDER_BLOCK, BRAIN_CORAL_BLOCK, BREWING_STAND, BRICK_BLOCK, BRICK_SLAB,
                BRICK_STAIRS, BROWN_CONCRETE, BROWN_CONCRETE_POWDER, BROWN_GLAZED_TERRACOTTA,
                BROWN_MUSHROOM_BLOCK, BROWN_SHULKER_BOX, BROWN_STAINED_GLASS, BROWN_STAINED_GLASS_PANE,
                BROWN_TERRACOTTA, BROWN_WOOL, BUBBLE_CORAL_BLOCK, CACTUS, CAKE, CALCITE, CAMERA,
                CARTOGRAPHY_TABLE, CARVED_PUMPKIN, CAULDRON, CHAIN_COMMAND_BLOCK, CHEMICAL_HEAT,
                CHERRY_BUTTON, CHERRY_DOOR, CHERRY_FENCE, CHERRY_FENCE_GATE, CHERRY_LEAVES, CHERRY_LOG,
                CHERRY_PLANKS, CHERRY_PRESSURE_PLATE, CHERRY_SLAB, CHERRY_STAIRS, CHERRY_STANDING_SIGN,
                CHERRY_TRAPDOOR, CHERRY_WALL_SIGN, CHERRY_WOOD, CHEST, CHISELED_DEEPSLATE,
                CHISELED_STONE_BRICKS, CHORUS_FLOWER, CHORUS_PLANT, CLAY, COAL_BLOCK, COAL_ORE,
                COARSE_DIRT, COBBLED_DEEPSLATE, COBBLESTONE, COBBLESTONE_SLAB, COBBLESTONE_WALL,
                COMMAND_BLOCK, COMPOSTER, COMPOUND_CREATOR, COPPER_BLOCK, COPPER_ORE,
                CRACKED_DEEPSLATE_BRICKS, CRACKED_DEEPSLATE_TILES, CRACKED_STONE_BRICKS, CRAFTING_TABLE,
                CRIMSON_BUTTON, CRIMSON_DOOR, CRIMSON_FENCE, CRIMSON_FENCE_GATE, CRIMSON_HYPHAE,
                CRIMSON_PLANKS, CRIMSON_PRESSURE_PLATE, CRIMSON_SLAB, CRIMSON_STAIRS,
                CRIMSON_STANDING_SIGN, CRIMSON_STEM, CRIMSON_TRAPDOOR, CRIMSON_WALL_SIGN, CRYING_OBSIDIAN,
                CUT_COPPER, CYAN_CONCRETE, CYAN_CONCRETE_POWDER, CYAN_GLAZED_TERRACOTTA, CYAN_SHULKER_BOX,
                CYAN_STAINED_GLASS, CYAN_STAINED_GLASS_PANE, CYAN_TERRACOTTA, CYAN_WOOL,
                DARKOAK_STANDING_SIGN, DARKOAK_WALL_SIGN, DARK_OAK_BUTTON, DARK_OAK_DOOR, DARK_OAK_FENCE,
                DARK_OAK_FENCE_GATE, DARK_OAK_LEAVES, DARK_OAK_LOG, DARK_OAK_PLANKS,
                DARK_OAK_PRESSURE_PLATE, DARK_OAK_SLAB, DARK_OAK_STAIRS, DARK_OAK_TRAPDOOR,
                DARK_OAK_WOOD, DAYLIGHT_DETECTOR, DEAD_BRAIN_CORAL_BLOCK, DEAD_BUBBLE_CORAL_BLOCK,
                DEAD_FIRE_CORAL_BLOCK, DEAD_HORN_CORAL_BLOCK, DEAD_TUBE_CORAL_BLOCK, DEEPSLATE_BRICKS,
                DEEPSLATE_COAL_ORE, DEEPSLATE_COPPER_ORE, DEEPSLATE_DIAMOND_ORE, DEEPSLATE_EMERALD_ORE,
                DEEPSLATE_GOLD_ORE, DEEPSLATE_IRON_ORE, DEEPSLATE_LAPIS_ORE, DEEPSLATE_REDSTONE_ORE,
                DEEPSLATE_TILES, DENY, DIAMOND_BLOCK, DIAMOND_ORE, DIRT, DIRT_WITH_ROOTS, DISPENSER,
                DRAGON_EGG, DRIED_KELP_BLOCK, DRIPSTONE_BLOCK, DROPPER, ELEMENT_0, EMERALD_BLOCK,
                EMERALD_ORE, ENCHANTING_TABLE, ENDER_CHEST, END_BRICKS, END_PORTAL_FRAME, END_STONE,
                FARMLAND, FIRE_CORAL_BLOCK, FLETCHING_TABLE, FROSTED_ICE, FURNACE, GILDED_BLACKSTONE,
                GLASS, GLASS_PANE, GLOWSTONE, GOLD_BLOCK, GOLD_ORE, GRASS_BLOCK, GRASS_PATH, GRAVEL,
                GRAY_CONCRETE, GRAY_CONCRETE_POWDER, GRAY_GLAZED_TERRACOTTA, GRAY_SHULKER_BOX,
                GRAY_STAINED_GLASS, GRAY_STAINED_GLASS_PANE, GRAY_TERRACOTTA, GRAY_WOOL, GREEN_CONCRETE,
                GREEN_CONCRETE_POWDER, GREEN_GLAZED_TERRACOTTA, GREEN_SHULKER_BOX, GREEN_STAINED_GLASS,
                GREEN_STAINED_GLASS_PANE, GREEN_TERRACOTTA, GREEN_WOOL, GRINDSTONE, HARDENED_CLAY,
                HARD_BLACK_STAINED_GLASS, HARD_BLACK_STAINED_GLASS_PANE, HARD_BLUE_STAINED_GLASS,
                HARD_BLUE_STAINED_GLASS_PANE, HARD_BROWN_STAINED_GLASS, HARD_BROWN_STAINED_GLASS_PANE,
                HARD_CYAN_STAINED_GLASS, HARD_CYAN_STAINED_GLASS_PANE, HARD_GLASS, HARD_GLASS_PANE,
                HARD_GRAY_STAINED_GLASS, HARD_GRAY_STAINED_GLASS_PANE, HARD_GREEN_STAINED_GLASS,
                HARD_GREEN_STAINED_GLASS_PANE, HARD_LIGHT_BLUE_STAINED_GLASS,
                HARD_LIGHT_BLUE_STAINED_GLASS_PANE, HARD_LIGHT_GRAY_STAINED_GLASS,
                HARD_LIGHT_GRAY_STAINED_GLASS_PANE, HARD_LIME_STAINED_GLASS, HARD_LIME_STAINED_GLASS_PANE,
                HARD_MAGENTA_STAINED_GLASS, HARD_MAGENTA_STAINED_GLASS_PANE, HARD_ORANGE_STAINED_GLASS,
                HARD_ORANGE_STAINED_GLASS_PANE, HARD_PINK_STAINED_GLASS, HARD_PINK_STAINED_GLASS_PANE,
                HARD_PURPLE_STAINED_GLASS, HARD_PURPLE_STAINED_GLASS_PANE, HARD_RED_STAINED_GLASS,
                HARD_RED_STAINED_GLASS_PANE, HARD_WHITE_STAINED_GLASS, HARD_WHITE_STAINED_GLASS_PANE,
                HARD_YELLOW_STAINED_GLASS, HARD_YELLOW_STAINED_GLASS_PANE, HAY_BLOCK,
                HEAVY_WEIGHTED_PRESSURE_PLATE, HONEYCOMB_BLOCK, HONEY_BLOCK, HOPPER, HORN_CORAL_BLOCK,
                ICE, INFESTED_CHISELED_STONE_BRICKS, INFESTED_COBBLESTONE, INFESTED_CRACKED_STONE_BRICKS,
                INFESTED_MOSSY_STONE_BRICKS, INFESTED_STONE, INFESTED_STONE_BRICKS, INFO_UPDATE,
                INFO_UPDATE2, INVISIBLE_BEDROCK, IRON_BARS, IRON_BLOCK, IRON_CHAIN, IRON_DOOR, IRON_ORE,
                IRON_TRAPDOOR, JIGSAW, JUKEBOX, JUNGLE_BUTTON, JUNGLE_DOOR, JUNGLE_FENCE,
                JUNGLE_FENCE_GATE, JUNGLE_LEAVES, JUNGLE_LOG, JUNGLE_PLANKS, JUNGLE_PRESSURE_PLATE,
                JUNGLE_SLAB, JUNGLE_STAIRS, JUNGLE_STANDING_SIGN, JUNGLE_TRAPDOOR, JUNGLE_WALL_SIGN,
                JUNGLE_WOOD, LANTERN, LAPIS_BLOCK, LAPIS_ORE, LECTERN, LIGHT_BLUE_CONCRETE,
                LIGHT_BLUE_CONCRETE_POWDER, LIGHT_BLUE_GLAZED_TERRACOTTA, LIGHT_BLUE_SHULKER_BOX,
                LIGHT_BLUE_STAINED_GLASS, LIGHT_BLUE_STAINED_GLASS_PANE, LIGHT_BLUE_TERRACOTTA,
                LIGHT_BLUE_WOOL, LIGHT_GRAY_CONCRETE, LIGHT_GRAY_CONCRETE_POWDER,
                LIGHT_GRAY_GLAZED_TERRACOTTA, LIGHT_GRAY_SHULKER_BOX, LIGHT_GRAY_STAINED_GLASS,
                LIGHT_GRAY_STAINED_GLASS_PANE, LIGHT_GRAY_TERRACOTTA, LIGHT_GRAY_WOOL,
                LIGHT_WEIGHTED_PRESSURE_PLATE, LIME_CONCRETE, LIME_CONCRETE_POWDER,
                LIME_GLAZED_TERRACOTTA, LIME_SHULKER_BOX, LIME_STAINED_GLASS, LIME_STAINED_GLASS_PANE,
                LIME_TERRACOTTA, LIME_WOOL, LODESTONE, LOOM, MAGENTA_CONCRETE, MAGENTA_CONCRETE_POWDER,
                MAGENTA_GLAZED_TERRACOTTA, MAGENTA_SHULKER_BOX, MAGENTA_STAINED_GLASS,
                MAGENTA_STAINED_GLASS_PANE, MAGENTA_TERRACOTTA, MAGENTA_WOOL, MAGMA, MANGROVE_BUTTON,
                MANGROVE_DOOR, MANGROVE_FENCE, MANGROVE_FENCE_GATE, MANGROVE_LEAVES, MANGROVE_LOG,
                MANGROVE_PLANKS, MANGROVE_PRESSURE_PLATE, MANGROVE_SLAB, MANGROVE_STAIRS,
                MANGROVE_STANDING_SIGN, MANGROVE_TRAPDOOR, MANGROVE_WALL_SIGN, MANGROVE_WOOD,
                MELON_BLOCK, MOB_SPAWNER, MOSSY_COBBLESTONE, MOSSY_STONE_BRICKS, MOSS_BLOCK,
                MOVING_BLOCK, MYCELIUM, NETHERITE_BLOCK, NETHERRACK, NETHER_BRICK, NETHER_BRICK_FENCE,
                NETHER_GOLD_ORE, NETHER_WART_BLOCK, NORMAL_STONE_SLAB, NORMAL_STONE_STAIRS, NOTE_BLOCK,
                OAK_BUTTON, OAK_DOOR, OAK_FENCE, OAK_FENCE_GATE, OAK_LEAVES, OAK_LOG, OAK_PLANKS,
                OAK_PRESSURE_PLATE, OAK_SLAB, OAK_STAIRS, OAK_STANDING_SIGN, OAK_TRAPDOOR,
                OAK_WALL_SIGN, OAK_WOOD, OBSERVER, OBSIDIAN, ORANGE_CONCRETE, ORANGE_CONCRETE_POWDER,
                ORANGE_GLAZED_TERRACOTTA, ORANGE_SHULKER_BOX, ORANGE_STAINED_GLASS,
                ORANGE_STAINED_GLASS_PANE, ORANGE_TERRACOTTA, ORANGE_WOOL, PACKED_ICE, PINK_CONCRETE,
                PINK_CONCRETE_POWDER, PINK_GLAZED_TERRACOTTA, PINK_SHULKER_BOX, PINK_STAINED_GLASS,
                PINK_STAINED_GLASS_PANE, PINK_TERRACOTTA, PINK_WOOL, PISTON, PISTON_ARM_COLLISION,
                PODZOL, POLISHED_BLACKSTONE, POLISHED_BLACKSTONE_BRICKS, POLISHED_BLACKSTONE_BUTTON,
                POLISHED_BLACKSTONE_PRESSURE_PLATE, POLISHED_DEEPSLATE, PRISMARINE, PUMPKIN,
                PURPLE_CONCRETE, PURPLE_CONCRETE_POWDER, PURPLE_GLAZED_TERRACOTTA, PURPLE_SHULKER_BOX,
                PURPLE_STAINED_GLASS, PURPLE_STAINED_GLASS_PANE, PURPLE_TERRACOTTA, PURPLE_WOOL,
                PURPUR_BLOCK, QUARTZ_BLOCK, QUARTZ_ORE, REDSTONE_BLOCK, REDSTONE_LAMP, REDSTONE_ORE,
                RED_CONCRETE, RED_CONCRETE_POWDER, RED_GLAZED_TERRACOTTA, RED_MUSHROOM_BLOCK, RED_SAND,
                RED_SANDSTONE, RED_SHULKER_BOX, RED_STAINED_GLASS, RED_STAINED_GLASS_PANE,
                RED_TERRACOTTA, RED_WOOL, REPEATING_COMMAND_BLOCK, RESERVED6, RESPAWN_ANCHOR, SAND,
                SANDSTONE, SEA_LANTERN, SHROOMLIGHT, SLIME, SMITHING_TABLE, SMOKER, SMOOTH_BASALT, SNOW,
                SOUL_SAND, SOUL_SOIL, SPONGE, SPORE_BLOSSOM, SPRUCE_BUTTON, SPRUCE_DOOR, SPRUCE_FENCE,
                SPRUCE_FENCE_GATE, SPRUCE_LEAVES, SPRUCE_LOG, SPRUCE_PLANKS, SPRUCE_PRESSURE_PLATE,
                SPRUCE_SLAB, SPRUCE_STAIRS, SPRUCE_STANDING_SIGN, SPRUCE_TRAPDOOR, SPRUCE_WALL_SIGN,
                SPRUCE_WOOD, STANDING_BANNER, STICKY_PISTON, STONE, STONECUTTER, STONECUTTER_BLOCK,
                STONE_BRICKS, STONE_BRICK_SLAB, STONE_BRICK_STAIRS, STONE_BUTTON, STONE_PRESSURE_PLATE,
                STONE_STAIRS, STRUCTURE_BLOCK, TARGET, TNT, TRAPPED_CHEST, TUBE_CORAL_BLOCK, TUFF,
                TURTLE_EGG, UNDYED_SHULKER_BOX, WALL_BANNER, WARPED_BUTTON, WARPED_DOOR, WARPED_FENCE,
                WARPED_FENCE_GATE, WARPED_HYPHAE, WARPED_PLANKS, WARPED_PRESSURE_PLATE, WARPED_SLAB,
                WARPED_STAIRS, WARPED_STANDING_SIGN, WARPED_STEM, WARPED_TRAPDOOR, WARPED_WALL_SIGN,
                WET_SPONGE, WHITE_CONCRETE, WHITE_CONCRETE_POWDER, WHITE_GLAZED_TERRACOTTA,
                WHITE_SHULKER_BOX, WHITE_STAINED_GLASS, WHITE_STAINED_GLASS_PANE, WHITE_TERRACOTTA,
                WHITE_WOOL, YELLOW_CONCRETE, YELLOW_CONCRETE_POWDER, YELLOW_GLAZED_TERRACOTTA,
                YELLOW_SHULKER_BOX, YELLOW_STAINED_GLASS, YELLOW_STAINED_GLASS_PANE, YELLOW_TERRACOTTA,
                YELLOW_WOOL
        );
    }

    private static void initTransparent() {
        tag(TRANSPARENT,
                ACACIA_LEAVES, ACACIA_SAPLING, AIR, ALLIUM, AMETHYST_CLUSTER, ANVIL, AZALEA,
                AZALEA_LEAVES, AZALEA_LEAVES_FLOWERED, AZURE_BLUET, BAMBOO, BAMBOO_SAPLING, BARRIER,
                BEACON, BED, BELL, BIG_DRIPLEAF, BIRCH_LEAVES, BIRCH_SAPLING, BLACK_CARPET, BLUE_CARPET,
                BLUE_ORCHID, BRAIN_CORAL, BRAIN_CORAL_FAN, BRAIN_CORAL_WALL_FAN, BREWING_STAND,
                BROWN_CARPET, BROWN_MUSHROOM, BUBBLE_COLUMN, BUBBLE_CORAL, BUBBLE_CORAL_FAN,
                BUBBLE_CORAL_WALL_FAN, CACTUS, CAKE, CALIBRATED_SCULK_SENSOR, CAMPFIRE, CAULDRON,
                CAVE_VINES, CAVE_VINES_BODY_WITH_BERRIES, CAVE_VINES_HEAD_WITH_BERRIES, CHERRY_LEAVES,
                CHERRY_SAPLING, CHEST, CHORUS_FLOWER, COCOA, CONDUIT, CORNFLOWER, CREEPER_HEAD,
                CRIMSON_FUNGUS, CRIMSON_ROOTS, CUT_COPPER_SLAB, CUT_COPPER_STAIRS, CYAN_CARPET,
                DANDELION, DARK_OAK_LEAVES, DARK_OAK_SAPLING, DAYLIGHT_DETECTOR,
                DAYLIGHT_DETECTOR_INVERTED, DEADBUSH, DEAD_BRAIN_CORAL, DEAD_BRAIN_CORAL_FAN,
                DEAD_BUBBLE_CORAL, DEAD_BUBBLE_CORAL_FAN, DEAD_FIRE_CORAL, DEAD_FIRE_CORAL_FAN,
                DEAD_HORN_CORAL, DEAD_HORN_CORAL_FAN, DEAD_TUBE_CORAL, DEAD_TUBE_CORAL_FAN, DRAGON_EGG,
                DRAGON_HEAD, ENCHANTING_TABLE, ENDER_CHEST, END_GATEWAY, END_PORTAL, END_PORTAL_FRAME,
                END_ROD, EXPOSED_CUT_COPPER_SLAB, EXPOSED_CUT_COPPER_STAIRS, FARMLAND, FERN, FIRE,
                FIRE_CORAL, FIRE_CORAL_FAN, FIRE_CORAL_WALL_FAN, FLOWERING_AZALEA, FLOWER_POT,
                FROSTED_ICE, GLASS_PANE, GLOWSTONE, GLOW_LICHEN, GRAY_CARPET, GREEN_CARPET, GRINDSTONE,
                HANGING_ROOTS, HONEY_BLOCK, HOPPER, HORN_CORAL, HORN_CORAL_FAN, HORN_CORAL_WALL_FAN,
                ICE, INVISIBLE_BEDROCK, IRON_BARS, IRON_CHAIN, JUNGLE_LEAVES, JUNGLE_SAPLING, LADDER,
                LANTERN, LARGE_AMETHYST_BUD, LARGE_FERN, LECTERN, LEVER, LIGHTNING_ROD, LIGHT_BLOCK_0,
                LIGHT_BLOCK_1, LIGHT_BLOCK_2, LIGHT_BLOCK_3, LIGHT_BLOCK_4, LIGHT_BLOCK_5, LIGHT_BLOCK_6,
                LIGHT_BLOCK_7, LIGHT_BLOCK_8, LIGHT_BLOCK_9, LIGHT_BLOCK_10, LIGHT_BLOCK_11,
                LIGHT_BLOCK_12, LIGHT_BLOCK_13, LIGHT_BLOCK_14, LIGHT_BLOCK_15, LIGHT_BLUE_CARPET,
                LIGHT_GRAY_CARPET, LILAC, LILY_OF_THE_VALLEY, LIME_CARPET, LIT_PUMPKIN, MAGENTA_CARPET,
                MANGROVE_LEAVES, MEDIUM_AMETHYST_BUD, MOSS_CARPET, MOVING_BLOCK, NETHER_SPROUTS,
                NETHER_WART, OAK_LEAVES, OAK_SAPLING, OBSERVER, ORANGE_CARPET, ORANGE_TULIP, OXEYE_DAISY,
                OXIDIZED_CUT_COPPER_SLAB, OXIDIZED_CUT_COPPER_STAIRS, PEONY, PIGLIN_HEAD, PINK_CARPET,
                PINK_TULIP, PISTON_ARM_COLLISION, PLAYER_HEAD, POINTED_DRIPSTONE, POPPY, PORTAL,
                POWDER_SNOW, POWERED_COMPARATOR, POWERED_REPEATER, PURPLE_CARPET, REDSTONE_LAMP,
                REDSTONE_TORCH, REDSTONE_WIRE, RED_CARPET, RED_MUSHROOM, RED_TULIP, REEDS, ROSE_BUSH,
                SCAFFOLDING, SCULK_SENSOR, SEAGRASS, SEA_LANTERN, SEA_PICKLE, SHORT_GRASS,
                SKELETON_SKULL, SMALL_AMETHYST_BUD, SMALL_DRIPLEAF_BLOCK, SNOW, SNOW_LAYER, SOUL_CAMPFIRE,
                SOUL_FIRE, SOUL_LANTERN, SOUL_TORCH, SPRUCE_LEAVES, SPRUCE_SAPLING, STANDING_BANNER,
                STONECUTTER, SUNFLOWER, SWEET_BERRY_BUSH, TALL_GRASS, TNT, TORCH, TRAPPED_CHEST,
                TRIPWIRE_HOOK, TRIP_WIRE, TUBE_CORAL, TUBE_CORAL_FAN, TUBE_CORAL_WALL_FAN, TURTLE_EGG,
                TWISTING_VINES, UNDYED_SHULKER_BOX, UNPOWERED_COMPARATOR, UNPOWERED_REPEATER, VINE,
                WALL_BANNER, WARPED_FUNGUS, WARPED_ROOTS, WATERLILY, WAXED_CUT_COPPER_SLAB,
                WAXED_CUT_COPPER_STAIRS, WAXED_EXPOSED_CUT_COPPER_SLAB, WAXED_EXPOSED_CUT_COPPER_STAIRS,
                WAXED_OXIDIZED_CUT_COPPER_SLAB, WAXED_OXIDIZED_CUT_COPPER_STAIRS,
                WAXED_WEATHERED_CUT_COPPER_SLAB, WAXED_WEATHERED_CUT_COPPER_STAIRS,
                WEATHERED_CUT_COPPER_SLAB, WEATHERED_CUT_COPPER_STAIRS, WEB, WEEPING_VINES, WHITE_CARPET,
                WHITE_TULIP, WITHER_ROSE, WITHER_SKELETON_SKULL, YELLOW_CARPET, ZOMBIE_HEAD
        );
    }

    private static void initStairs() {
        tag(STAIRS,
                ACACIA_STAIRS, ANDESITE_STAIRS, BAMBOO_MOSAIC_STAIRS, BAMBOO_STAIRS, BIRCH_STAIRS,
                BLACKSTONE_STAIRS, BRICK_STAIRS, CHERRY_STAIRS, COBBLED_DEEPSLATE_STAIRS, CRIMSON_STAIRS,
                CUT_COPPER_STAIRS, DARK_OAK_STAIRS, DARK_PRISMARINE_STAIRS, DEEPSLATE_BRICK_STAIRS,
                DEEPSLATE_TILE_STAIRS, DIORITE_STAIRS, END_BRICK_STAIRS, EXPOSED_CUT_COPPER_STAIRS,
                GRANITE_STAIRS, JUNGLE_STAIRS, MANGROVE_STAIRS, MOSSY_COBBLESTONE_STAIRS,
                MOSSY_STONE_BRICK_STAIRS, MUD_BRICK_STAIRS, NETHER_BRICK_STAIRS, NORMAL_STONE_STAIRS,
                OAK_STAIRS, OXIDIZED_CUT_COPPER_STAIRS, PALE_OAK_STAIRS, POLISHED_ANDESITE_STAIRS,
                POLISHED_BLACKSTONE_BRICK_STAIRS, POLISHED_BLACKSTONE_STAIRS, POLISHED_DEEPSLATE_STAIRS,
                POLISHED_DIORITE_STAIRS, POLISHED_GRANITE_STAIRS, POLISHED_TUFF_STAIRS,
                PRISMARINE_BRICKS_STAIRS, PRISMARINE_STAIRS, PURPUR_STAIRS, QUARTZ_STAIRS,
                RED_NETHER_BRICK_STAIRS, RED_SANDSTONE_STAIRS, RESIN_BRICK_STAIRS, SANDSTONE_STAIRS,
                SMOOTH_QUARTZ_STAIRS, SMOOTH_RED_SANDSTONE_STAIRS, SMOOTH_SANDSTONE_STAIRS, SPRUCE_STAIRS,
                STONE_BRICK_STAIRS, STONE_STAIRS, TUFF_BRICK_STAIRS, TUFF_STAIRS, WARPED_STAIRS,
                WAXED_CUT_COPPER_STAIRS, WAXED_EXPOSED_CUT_COPPER_STAIRS, WAXED_OXIDIZED_CUT_COPPER_STAIRS,
                WAXED_WEATHERED_CUT_COPPER_STAIRS, WEATHERED_CUT_COPPER_STAIRS
        );
    }

    private static void initSlab() {
        tag(SLAB,
                ACACIA_SLAB, ANDESITE_SLAB, BAMBOO_MOSAIC_SLAB, BAMBOO_SLAB, BIRCH_SLAB,
                BLACKSTONE_SLAB, BRICK_SLAB, CHERRY_SLAB, COBBLED_DEEPSLATE_SLAB, COBBLESTONE_SLAB,
                CRIMSON_SLAB, CUT_COPPER_SLAB, CUT_RED_SANDSTONE_SLAB, CUT_SANDSTONE_SLAB,
                DARK_OAK_SLAB, DARK_PRISMARINE_SLAB, DEEPSLATE_BRICK_SLAB, DEEPSLATE_TILE_SLAB,
                DIORITE_SLAB, END_STONE_BRICK_SLAB, EXPOSED_CUT_COPPER_SLAB, GRANITE_SLAB,
                JUNGLE_SLAB, MANGROVE_SLAB, MOSSY_COBBLESTONE_SLAB, MOSSY_STONE_BRICK_SLAB,
                MUD_BRICK_SLAB, NETHER_BRICK_SLAB, NORMAL_STONE_SLAB, OAK_SLAB,
                OXIDIZED_CUT_COPPER_SLAB, PALE_OAK_SLAB, PETRIFIED_OAK_SLAB,
                POLISHED_ANDESITE_SLAB, POLISHED_BLACKSTONE_BRICK_SLAB, POLISHED_BLACKSTONE_SLAB,
                POLISHED_DEEPSLATE_SLAB, POLISHED_DIORITE_SLAB, POLISHED_GRANITE_SLAB,
                POLISHED_TUFF_SLAB, PRISMARINE_BRICK_SLAB, PRISMARINE_SLAB, PURPUR_SLAB,
                QUARTZ_SLAB, RED_NETHER_BRICK_SLAB, RED_SANDSTONE_SLAB, RESIN_BRICK_SLAB,
                SANDSTONE_SLAB, SMOOTH_QUARTZ_SLAB, SMOOTH_RED_SANDSTONE_SLAB, SMOOTH_SANDSTONE_SLAB,
                SMOOTH_STONE_SLAB, SPRUCE_SLAB, STONE_BRICK_SLAB, TUFF_BRICK_SLAB, TUFF_SLAB,
                WARPED_SLAB, WAXED_CUT_COPPER_SLAB, WAXED_EXPOSED_CUT_COPPER_SLAB,
                WAXED_OXIDIZED_CUT_COPPER_SLAB, WAXED_WEATHERED_CUT_COPPER_SLAB,
                WEATHERED_CUT_COPPER_SLAB
        );
    }

    private static void initDoubleSlab() {
        tag(DOUBLE_SLAB,
                ACACIA_DOUBLE_SLAB, ANDESITE_DOUBLE_SLAB, BAMBOO_DOUBLE_SLAB, BAMBOO_MOSAIC_DOUBLE_SLAB,
                BIRCH_DOUBLE_SLAB, BLACKSTONE_DOUBLE_SLAB, BRICK_DOUBLE_SLAB, CHERRY_DOUBLE_SLAB,
                COBBLED_DEEPSLATE_DOUBLE_SLAB, COBBLESTONE_DOUBLE_SLAB, CRIMSON_DOUBLE_SLAB,
                CUT_RED_SANDSTONE_DOUBLE_SLAB, CUT_SANDSTONE_DOUBLE_SLAB, DARK_OAK_DOUBLE_SLAB,
                DARK_PRISMARINE_DOUBLE_SLAB, DEEPSLATE_BRICK_DOUBLE_SLAB, DEEPSLATE_TILE_DOUBLE_SLAB,
                DIORITE_DOUBLE_SLAB, END_STONE_BRICK_DOUBLE_SLAB, GRANITE_DOUBLE_SLAB,
                JUNGLE_DOUBLE_SLAB, MANGROVE_DOUBLE_SLAB, MOSSY_COBBLESTONE_DOUBLE_SLAB,
                MOSSY_STONE_BRICK_DOUBLE_SLAB, MUD_BRICK_DOUBLE_SLAB, NETHER_BRICK_DOUBLE_SLAB,
                NORMAL_STONE_DOUBLE_SLAB, OAK_DOUBLE_SLAB, PALE_OAK_DOUBLE_SLAB,
                PETRIFIED_OAK_DOUBLE_SLAB, POLISHED_ANDESITE_DOUBLE_SLAB,
                POLISHED_BLACKSTONE_BRICK_DOUBLE_SLAB, POLISHED_BLACKSTONE_DOUBLE_SLAB,
                POLISHED_DEEPSLATE_DOUBLE_SLAB, POLISHED_DIORITE_DOUBLE_SLAB,
                POLISHED_GRANITE_DOUBLE_SLAB, POLISHED_TUFF_DOUBLE_SLAB, PRISMARINE_BRICK_DOUBLE_SLAB,
                PRISMARINE_DOUBLE_SLAB, PURPUR_DOUBLE_SLAB, QUARTZ_DOUBLE_SLAB,
                RED_NETHER_BRICK_DOUBLE_SLAB, RED_SANDSTONE_DOUBLE_SLAB, RESIN_BRICK_DOUBLE_SLAB,
                SANDSTONE_DOUBLE_SLAB, SMOOTH_QUARTZ_DOUBLE_SLAB, SMOOTH_RED_SANDSTONE_DOUBLE_SLAB,
                SMOOTH_SANDSTONE_DOUBLE_SLAB, SMOOTH_STONE_DOUBLE_SLAB, SPRUCE_DOUBLE_SLAB,
                STONE_BRICK_DOUBLE_SLAB, TUFF_BRICK_DOUBLE_SLAB, TUFF_DOUBLE_SLAB,
                WARPED_DOUBLE_SLAB
        );
    }

    private static void initDoor() {
        tag(DOOR,
                ACACIA_DOOR, BAMBOO_DOOR, BIRCH_DOOR, CHERRY_DOOR, CRIMSON_DOOR, DARK_OAK_DOOR,
                IRON_DOOR, JUNGLE_DOOR, MANGROVE_DOOR, OAK_DOOR, SPRUCE_DOOR, WARPED_DOOR
        );
    }

    private static void initTrapdoor() {
        tag(TRAPDOOR,
                ACACIA_TRAPDOOR, BAMBOO_TRAPDOOR, BIRCH_TRAPDOOR, CHERRY_TRAPDOOR, CRIMSON_TRAPDOOR,
                DARK_OAK_TRAPDOOR, IRON_TRAPDOOR, JUNGLE_TRAPDOOR, MANGROVE_TRAPDOOR, OAK_TRAPDOOR,
                SPRUCE_TRAPDOOR, WARPED_TRAPDOOR
        );
    }

    private static void initLiquid() {
        tag(LIQUID, FLOWING_LAVA, FLOWING_WATER, LAVA, WATER);
    }

    private static void initCrops() {
        tag(CROPS,
                BAMBOO, BEETROOT, BROWN_MUSHROOM, CACTUS, CARROTS, CHORUS_PLANT, COCOA, KELP,
                MELON_STEM, NETHER_WART, POTATOES, PUMPKIN_STEM, RED_MUSHROOM, REEDS, SEA_PICKLE,
                SWEET_BERRY_BUSH, WHEAT
        );
    }

    private static void initWalls() {
        tag(WALLS,
                BLACKSTONE_WALL, BRICK_WALL, COBBLED_DEEPSLATE_WALL, COBBLESTONE_WALL,
                DEEPSLATE_BRICK_WALL, DEEPSLATE_TILE_WALL, END_STONE_BRICK_WALL, MOSSY_COBBLESTONE_WALL,
                MOSSY_STONE_BRICK_WALL, NETHER_BRICK_WALL, POLISHED_BLACKSTONE_BRICK_WALL,
                POLISHED_BLACKSTONE_WALL, POLISHED_DEEPSLATE_WALL, PRISMARINE_WALL, RED_NETHER_BRICK_WALL,
                RED_SANDSTONE_WALL, SANDSTONE_WALL, STONE_BRICK_WALL
        );
    }

    private static void initSign() {
        tag(SIGN,
                ACACIA_HANGING_SIGN, ACACIA_STANDING_SIGN, ACACIA_WALL_SIGN, BAMBOO_HANGING_SIGN,
                BAMBOO_STANDING_SIGN, BAMBOO_WALL_SIGN, BIRCH_HANGING_SIGN, BIRCH_STANDING_SIGN,
                BIRCH_WALL_SIGN, CHERRY_HANGING_SIGN, CHERRY_STANDING_SIGN, CHERRY_WALL_SIGN,
                CRIMSON_HANGING_SIGN, CRIMSON_STANDING_SIGN, CRIMSON_WALL_SIGN, DARKOAK_STANDING_SIGN,
                DARKOAK_WALL_SIGN, DARK_OAK_HANGING_SIGN, JUNGLE_HANGING_SIGN, JUNGLE_STANDING_SIGN,
                JUNGLE_WALL_SIGN, MANGROVE_HANGING_SIGN, MANGROVE_STANDING_SIGN, MANGROVE_WALL_SIGN,
                OAK_HANGING_SIGN, OAK_STANDING_SIGN, OAK_WALL_SIGN, SPRUCE_HANGING_SIGN,
                SPRUCE_STANDING_SIGN, SPRUCE_WALL_SIGN, WARPED_HANGING_SIGN, WARPED_STANDING_SIGN,
                WARPED_WALL_SIGN
        );
    }

    private static void initStem() {
        tag(STEM, MELON_STEM, PUMPKIN_STEM);
    }

    private static void initButton() {
        tag(BUTTON,
                ACACIA_BUTTON, BAMBOO_BUTTON, BIRCH_BUTTON, CHERRY_BUTTON, CRIMSON_BUTTON,
                DARK_OAK_BUTTON, JUNGLE_BUTTON, MANGROVE_BUTTON, OAK_BUTTON, POLISHED_BLACKSTONE_BUTTON,
                SPRUCE_BUTTON, STONE_BUTTON, WARPED_BUTTON
        );
    }

    private static void initPressurePlate() {
        tag(PRESSURE_PLATE,
                ACACIA_PRESSURE_PLATE, BAMBOO_PRESSURE_PLATE, BIRCH_PRESSURE_PLATE,
                CHERRY_PRESSURE_PLATE, CRIMSON_PRESSURE_PLATE, DARK_OAK_PRESSURE_PLATE,
                HEAVY_WEIGHTED_PRESSURE_PLATE, JUNGLE_PRESSURE_PLATE, LIGHT_WEIGHTED_PRESSURE_PLATE,
                MANGROVE_PRESSURE_PLATE, OAK_PRESSURE_PLATE, POLISHED_BLACKSTONE_PRESSURE_PLATE,
                SPRUCE_PRESSURE_PLATE, STONE_PRESSURE_PLATE, WARPED_PRESSURE_PLATE
        );
    }

    private static void initRail() {
        tag(RAIL, ACTIVATOR_RAIL, DETECTOR_RAIL, GOLDEN_RAIL, BlockTypes.RAIL);
    }

    private static void initGround() {
        tag(GROUND, COARSE_DIRT, DIRT, FARMLAND, GRASS_BLOCK, MUD, MUDDY_MANGROVE_ROOTS, MYCELIUM, PODZOL);
    }

    private static void initFence() {
        tag(FENCE,
                ACACIA_FENCE, BAMBOO_FENCE, BIRCH_FENCE, CHERRY_FENCE, CRIMSON_FENCE, DARK_OAK_FENCE,
                JUNGLE_FENCE, MANGROVE_FENCE, NETHER_BRICK_FENCE, OAK_FENCE, SPRUCE_FENCE, WARPED_FENCE
        );
    }

    private static void initFenceGate() {
        tag(FENCE_GATE,
                ACACIA_FENCE_GATE, BAMBOO_FENCE_GATE, BIRCH_FENCE_GATE, CHERRY_FENCE_GATE,
                CRIMSON_FENCE_GATE, DARK_OAK_FENCE_GATE, JUNGLE_FENCE_GATE, MANGROVE_FENCE_GATE,
                OAK_FENCE_GATE, SPRUCE_FENCE_GATE, WARPED_FENCE_GATE
        );
    }

    private static void initWool() {
        tag(WOOL,
                BLACK_WOOL, BLUE_WOOL, BROWN_WOOL, CYAN_WOOL, GRAY_WOOL, GREEN_WOOL, LIGHT_BLUE_WOOL,
                LIGHT_GRAY_WOOL, LIME_WOOL, MAGENTA_WOOL, ORANGE_WOOL, PINK_WOOL, PURPLE_WOOL, RED_WOOL,
                WHITE_WOOL, YELLOW_WOOL
        );
    }

    private static void initLog() {
        tag(LOG,
                ACACIA_LOG, BIRCH_LOG, CHERRY_LOG, CRIMSON_STEM, DARK_OAK_LOG, JUNGLE_LOG,
                MANGROVE_LOG, OAK_LOG, PALE_OAK_LOG, SPRUCE_LOG, STRIPPED_ACACIA_LOG, STRIPPED_BIRCH_LOG,
                STRIPPED_CHERRY_LOG, STRIPPED_CRIMSON_STEM, STRIPPED_DARK_OAK_LOG, STRIPPED_JUNGLE_LOG,
                STRIPPED_MANGROVE_LOG, STRIPPED_OAK_LOG, STRIPPED_SPRUCE_LOG, STRIPPED_WARPED_STEM,
                WARPED_STEM
        );
    }

    private static void initPlanks() {
        tag(PLANKS,
                ACACIA_PLANKS, BAMBOO_MOSAIC, BAMBOO_PLANKS, BIRCH_PLANKS, CHERRY_PLANKS, CRIMSON_PLANKS,
                DARK_OAK_PLANKS, JUNGLE_PLANKS, MANGROVE_PLANKS, OAK_PLANKS, PALE_OAK_PLANKS,
                SPRUCE_PLANKS, WARPED_PLANKS
        );
    }

    private static void initSapling() {
        tag(SAPLING,
                ACACIA_SAPLING, BAMBOO_SAPLING, BIRCH_SAPLING, CHERRY_SAPLING, DARK_OAK_SAPLING,
                JUNGLE_SAPLING, OAK_SAPLING, PALE_OAK_SAPLING, SPRUCE_SAPLING
        );
    }

    private static void initLeaves() {
        tag(LEAVES,
                ACACIA_LEAVES, AZALEA_LEAVES, AZALEA_LEAVES_FLOWERED, BIRCH_LEAVES, CHERRY_LEAVES,
                DARK_OAK_LEAVES, JUNGLE_LEAVES, MANGROVE_LEAVES, OAK_LEAVES, PALE_OAK_LEAVES,
                SPRUCE_LEAVES
        );
    }
}
