package org.cloudburstmc.api.level.biome;

import lombok.experimental.UtilityClass;
import org.cloudburstmc.api.internal.BuiltInTypeCatalog;
import org.cloudburstmc.api.util.Identifier;

import java.util.List;
import java.util.Optional;

/**
 * Generated by {@code BiomeDataGen}, do not edit by hand.
 */
@UtilityClass
public class BiomeTypes {
    private static final BuiltInTypeCatalog<BiomeType> TYPES = BuiltInTypeCatalog.create(BiomeType::getId);

    public static final BiomeType BAMBOO_JUNGLE = type("bamboo_jungle");
    public static final BiomeType BAMBOO_JUNGLE_HILLS = type("bamboo_jungle_hills");
    public static final BiomeType BASALT_DELTAS = type("basalt_deltas");
    public static final BiomeType BEACH = type("beach");
    public static final BiomeType BIRCH_FOREST = type("birch_forest");
    public static final BiomeType BIRCH_FOREST_HILLS = type("birch_forest_hills");
    public static final BiomeType BIRCH_FOREST_HILLS_MUTATED = type("birch_forest_hills_mutated");
    public static final BiomeType BIRCH_FOREST_MUTATED = type("birch_forest_mutated");
    public static final BiomeType CHERRY_GROVE = type("cherry_grove");
    public static final BiomeType COLD_BEACH = type("cold_beach");
    public static final BiomeType COLD_OCEAN = type("cold_ocean");
    public static final BiomeType COLD_TAIGA = type("cold_taiga");
    public static final BiomeType COLD_TAIGA_HILLS = type("cold_taiga_hills");
    public static final BiomeType COLD_TAIGA_MUTATED = type("cold_taiga_mutated");
    public static final BiomeType CRIMSON_FOREST = type("crimson_forest");
    public static final BiomeType DAPPLED_FOREST = type("dappled_forest");
    public static final BiomeType DEEP_COLD_OCEAN = type("deep_cold_ocean");
    public static final BiomeType DEEP_DARK = type("deep_dark");
    public static final BiomeType DEEP_FROZEN_OCEAN = type("deep_frozen_ocean");
    public static final BiomeType DEEP_LUKEWARM_OCEAN = type("deep_lukewarm_ocean");
    public static final BiomeType DEEP_OCEAN = type("deep_ocean");
    public static final BiomeType DEEP_WARM_OCEAN = type("deep_warm_ocean");
    public static final BiomeType DESERT = type("desert");
    public static final BiomeType DESERT_HILLS = type("desert_hills");
    public static final BiomeType DESERT_MUTATED = type("desert_mutated");
    public static final BiomeType DRIPSTONE_CAVES = type("dripstone_caves");
    public static final BiomeType EXTREME_HILLS = type("extreme_hills");
    public static final BiomeType EXTREME_HILLS_EDGE = type("extreme_hills_edge");
    public static final BiomeType EXTREME_HILLS_MUTATED = type("extreme_hills_mutated");
    public static final BiomeType EXTREME_HILLS_PLUS_TREES = type("extreme_hills_plus_trees");
    public static final BiomeType EXTREME_HILLS_PLUS_TREES_MUTATED = type("extreme_hills_plus_trees_mutated");
    public static final BiomeType FLOWER_FOREST = type("flower_forest");
    public static final BiomeType FOREST = type("forest");
    public static final BiomeType FOREST_HILLS = type("forest_hills");
    public static final BiomeType FROZEN_OCEAN = type("frozen_ocean");
    public static final BiomeType FROZEN_PEAKS = type("frozen_peaks");
    public static final BiomeType FROZEN_RIVER = type("frozen_river");
    public static final BiomeType GROVE = type("grove");
    public static final BiomeType HELL = type("hell");
    public static final BiomeType ICE_MOUNTAINS = type("ice_mountains");
    public static final BiomeType ICE_PLAINS = type("ice_plains");
    public static final BiomeType ICE_PLAINS_SPIKES = type("ice_plains_spikes");
    public static final BiomeType JAGGED_PEAKS = type("jagged_peaks");
    public static final BiomeType JUNGLE = type("jungle");
    public static final BiomeType JUNGLE_EDGE = type("jungle_edge");
    public static final BiomeType JUNGLE_EDGE_MUTATED = type("jungle_edge_mutated");
    public static final BiomeType JUNGLE_HILLS = type("jungle_hills");
    public static final BiomeType JUNGLE_MUTATED = type("jungle_mutated");
    public static final BiomeType LEGACY_FROZEN_OCEAN = type("legacy_frozen_ocean");
    public static final BiomeType LUKEWARM_OCEAN = type("lukewarm_ocean");
    public static final BiomeType LUSH_CAVES = type("lush_caves");
    public static final BiomeType MANGROVE_SWAMP = type("mangrove_swamp");
    public static final BiomeType MEADOW = type("meadow");
    public static final BiomeType MEGA_TAIGA = type("mega_taiga");
    public static final BiomeType MEGA_TAIGA_HILLS = type("mega_taiga_hills");
    public static final BiomeType MESA = type("mesa");
    public static final BiomeType MESA_BRYCE = type("mesa_bryce");
    public static final BiomeType MESA_PLATEAU = type("mesa_plateau");
    public static final BiomeType MESA_PLATEAU_MUTATED = type("mesa_plateau_mutated");
    public static final BiomeType MESA_PLATEAU_STONE = type("mesa_plateau_stone");
    public static final BiomeType MESA_PLATEAU_STONE_MUTATED = type("mesa_plateau_stone_mutated");
    public static final BiomeType MUSHROOM_ISLAND = type("mushroom_island");
    public static final BiomeType MUSHROOM_ISLAND_SHORE = type("mushroom_island_shore");
    public static final BiomeType OCEAN = type("ocean");
    public static final BiomeType PALE_GARDEN = type("pale_garden");
    public static final BiomeType PLAINS = type("plains");
    public static final BiomeType REDWOOD_TAIGA_HILLS_MUTATED = type("redwood_taiga_hills_mutated");
    public static final BiomeType REDWOOD_TAIGA_MUTATED = type("redwood_taiga_mutated");
    public static final BiomeType RIVER = type("river");
    public static final BiomeType ROOFED_FOREST = type("roofed_forest");
    public static final BiomeType ROOFED_FOREST_MUTATED = type("roofed_forest_mutated");
    public static final BiomeType SAVANNA = type("savanna");
    public static final BiomeType SAVANNA_MUTATED = type("savanna_mutated");
    public static final BiomeType SAVANNA_PLATEAU = type("savanna_plateau");
    public static final BiomeType SAVANNA_PLATEAU_MUTATED = type("savanna_plateau_mutated");
    public static final BiomeType SNOWY_SLOPES = type("snowy_slopes");
    public static final BiomeType SOULSAND_VALLEY = type("soulsand_valley");
    public static final BiomeType STONE_BEACH = type("stone_beach");
    public static final BiomeType STONY_PEAKS = type("stony_peaks");
    public static final BiomeType SULFUR_CAVES = type("sulfur_caves");
    public static final BiomeType SUNFLOWER_PLAINS = type("sunflower_plains");
    public static final BiomeType SWAMPLAND = type("swampland");
    public static final BiomeType SWAMPLAND_MUTATED = type("swampland_mutated");
    public static final BiomeType TAIGA = type("taiga");
    public static final BiomeType TAIGA_HILLS = type("taiga_hills");
    public static final BiomeType TAIGA_MUTATED = type("taiga_mutated");
    public static final BiomeType THE_END = type("the_end");
    public static final BiomeType WARM_OCEAN = type("warm_ocean");
    public static final BiomeType WARPED_FOREST = type("warped_forest");

    /**
     * Returns a built-in biome type.
     *
     * @param id biome identifier
     * @return matching biome type, if present
     */
    public static Optional<BiomeType> get(Identifier id) {
        return TYPES.get(id);
    }

    /**
     * Returns all built-in biome types.
     *
     * @return biome types in declaration order
     */
    public static List<BiomeType> values() {
        return TYPES.values();
    }

    private static BiomeType type(String id) {
        return TYPES.register(BiomeType.of(Identifier.parse(id)));
    }
}
