package org.cloudburstmc.api.level.biome;

import lombok.experimental.UtilityClass;
import org.cloudburstmc.api.internal.BuiltInTypeCatalog;
import org.cloudburstmc.api.util.Identifier;

import java.util.List;
import java.util.Optional;

/**
 * Generated by {@code BiomeDataGen}, do not edit by hand.
 */
@UtilityClass
public class BiomeBehaviorComponentTypes {
    private static final BuiltInTypeCatalog<BiomeBehaviorComponentType> TYPES = BuiltInTypeCatalog.create(BiomeBehaviorComponentType::getId);

    public static final BiomeBehaviorComponentType CLIMATE = type("climate");
    public static final BiomeBehaviorComponentType CREATURE_SPAWN_PROBABILITY = type("creature_spawn_probability");
    public static final BiomeBehaviorComponentType HUMIDITY = type("humidity");
    public static final BiomeBehaviorComponentType MAP_TINTS = type("map_tints");
    public static final BiomeBehaviorComponentType MOUNTAIN_PARAMETERS = type("mountain_parameters");
    public static final BiomeBehaviorComponentType MULTINOISE_GENERATION_RULES = type("multinoise_generation_rules");
    public static final BiomeBehaviorComponentType OVERWORLD_GENERATION_RULES = type("overworld_generation_rules");
    public static final BiomeBehaviorComponentType OVERWORLD_HEIGHT = type("overworld_height");
    public static final BiomeBehaviorComponentType PARTIALLY_FROZEN = type("partially_frozen");
    public static final BiomeBehaviorComponentType SUBSURFACE_BUILDER = type("subsurface_builder");
    public static final BiomeBehaviorComponentType SURFACE_BUILDER = type("surface_builder");
    public static final BiomeBehaviorComponentType SURFACE_MATERIAL_ADJUSTMENTS = type("surface_material_adjustments");
    public static final BiomeBehaviorComponentType TAGS = type("tags");
    public static final BiomeBehaviorComponentType VILLAGE_TYPE = type("village_type");

    /**
     * Returns a built-in biome behavior component type.
     *
     * @param id component identifier
     * @return matching component type, if present
     */
    public static Optional<BiomeBehaviorComponentType> get(Identifier id) {
        return TYPES.get(id);
    }

    /**
     * Returns all built-in biome behavior component types.
     *
     * @return component types in declaration order
     */
    public static List<BiomeBehaviorComponentType> values() {
        return TYPES.values();
    }

    private static BiomeBehaviorComponentType type(String id) {
        return TYPES.register(BiomeBehaviorComponentType.of(Identifier.parse(id)));
    }
}
