package org.cloudburstmc.api.level.biome;

import lombok.experimental.UtilityClass;
import org.cloudburstmc.api.internal.BuiltInTypeCatalog;
import org.cloudburstmc.api.util.Identifier;

import java.util.List;
import java.util.Optional;

/**
 * Generated by {@code BiomeDataGen}, do not edit by hand.
 */
@UtilityClass
public class BiomeAppearanceComponentTypes {
    private static final BuiltInTypeCatalog<BiomeAppearanceComponentType> TYPES = BuiltInTypeCatalog.create(BiomeAppearanceComponentType::getId);

    public static final BiomeAppearanceComponentType AMBIENT_SOUNDS = type("ambient_sounds");
    public static final BiomeAppearanceComponentType ATMOSPHERE_IDENTIFIER = type("atmosphere_identifier");
    public static final BiomeAppearanceComponentType BIOME_MUSIC = type("biome_music");
    public static final BiomeAppearanceComponentType COLOR_GRADING_IDENTIFIER = type("color_grading_identifier");
    public static final BiomeAppearanceComponentType DRY_FOLIAGE_COLOR = type("dry_foliage_color");
    public static final BiomeAppearanceComponentType FOG_APPEARANCE = type("fog_appearance");
    public static final BiomeAppearanceComponentType FOLIAGE_APPEARANCE = type("foliage_appearance");
    public static final BiomeAppearanceComponentType GRASS_APPEARANCE = type("grass_appearance");
    public static final BiomeAppearanceComponentType LIGHTING_IDENTIFIER = type("lighting_identifier");
    public static final BiomeAppearanceComponentType PRECIPITATION = type("precipitation");
    public static final BiomeAppearanceComponentType SKY_COLOR = type("sky_color");
    public static final BiomeAppearanceComponentType WATER_APPEARANCE = type("water_appearance");
    public static final BiomeAppearanceComponentType WATER_IDENTIFIER = type("water_identifier");

    /**
     * Returns a built-in biome appearance component type.
     *
     * @param id component identifier
     * @return matching component type, if present
     */
    public static Optional<BiomeAppearanceComponentType> get(Identifier id) {
        return TYPES.get(id);
    }

    /**
     * Returns all built-in biome appearance component types.
     *
     * @return component types in declaration order
     */
    public static List<BiomeAppearanceComponentType> values() {
        return TYPES.values();
    }

    private static BiomeAppearanceComponentType type(String id) {
        return TYPES.register(BiomeAppearanceComponentType.of(Identifier.parse(id)));
    }
}
