package org.cloudburstmc.server.registry;

import lombok.experimental.UtilityClass;

import java.util.List;

import static org.cloudburstmc.api.block.BlockTypes.*;

@UtilityClass
public class VanillaBlockFamilies {

    public static final List<VanillaSlabAndStairFamily> COLORED_BUILDING_BLOCKS = List.of(
            new VanillaSlabAndStairFamily(BLACK_CONCRETE, BLACK_CONCRETE_SLAB, BLACK_CONCRETE_DOUBLE_SLAB, BLACK_CONCRETE_STAIRS),
            new VanillaSlabAndStairFamily(BLACK_WOOL, BLACK_WOOL_SLAB, BLACK_WOOL_DOUBLE_SLAB, BLACK_WOOL_STAIRS),
            new VanillaSlabAndStairFamily(BLUE_CONCRETE, BLUE_CONCRETE_SLAB, BLUE_CONCRETE_DOUBLE_SLAB, BLUE_CONCRETE_STAIRS),
            new VanillaSlabAndStairFamily(BLUE_WOOL, BLUE_WOOL_SLAB, BLUE_WOOL_DOUBLE_SLAB, BLUE_WOOL_STAIRS),
            new VanillaSlabAndStairFamily(BROWN_CONCRETE, BROWN_CONCRETE_SLAB, BROWN_CONCRETE_DOUBLE_SLAB, BROWN_CONCRETE_STAIRS),
            new VanillaSlabAndStairFamily(BROWN_WOOL, BROWN_WOOL_SLAB, BROWN_WOOL_DOUBLE_SLAB, BROWN_WOOL_STAIRS),
            new VanillaSlabAndStairFamily(CYAN_CONCRETE, CYAN_CONCRETE_SLAB, CYAN_CONCRETE_DOUBLE_SLAB, CYAN_CONCRETE_STAIRS),
            new VanillaSlabAndStairFamily(CYAN_WOOL, CYAN_WOOL_SLAB, CYAN_WOOL_DOUBLE_SLAB, CYAN_WOOL_STAIRS),
            new VanillaSlabAndStairFamily(GRAY_CONCRETE, GRAY_CONCRETE_SLAB, GRAY_CONCRETE_DOUBLE_SLAB, GRAY_CONCRETE_STAIRS),
            new VanillaSlabAndStairFamily(GRAY_WOOL, GRAY_WOOL_SLAB, GRAY_WOOL_DOUBLE_SLAB, GRAY_WOOL_STAIRS),
            new VanillaSlabAndStairFamily(GREEN_CONCRETE, GREEN_CONCRETE_SLAB, GREEN_CONCRETE_DOUBLE_SLAB, GREEN_CONCRETE_STAIRS),
            new VanillaSlabAndStairFamily(GREEN_WOOL, GREEN_WOOL_SLAB, GREEN_WOOL_DOUBLE_SLAB, GREEN_WOOL_STAIRS),
            new VanillaSlabAndStairFamily(LIGHT_BLUE_CONCRETE, LIGHT_BLUE_CONCRETE_SLAB, LIGHT_BLUE_CONCRETE_DOUBLE_SLAB, LIGHT_BLUE_CONCRETE_STAIRS),
            new VanillaSlabAndStairFamily(LIGHT_BLUE_WOOL, LIGHT_BLUE_WOOL_SLAB, LIGHT_BLUE_WOOL_DOUBLE_SLAB, LIGHT_BLUE_WOOL_STAIRS),
            new VanillaSlabAndStairFamily(LIGHT_GRAY_CONCRETE, LIGHT_GRAY_CONCRETE_SLAB, LIGHT_GRAY_CONCRETE_DOUBLE_SLAB, LIGHT_GRAY_CONCRETE_STAIRS),
            new VanillaSlabAndStairFamily(LIGHT_GRAY_WOOL, LIGHT_GRAY_WOOL_SLAB, LIGHT_GRAY_WOOL_DOUBLE_SLAB, LIGHT_GRAY_WOOL_STAIRS),
            new VanillaSlabAndStairFamily(LIME_CONCRETE, LIME_CONCRETE_SLAB, LIME_CONCRETE_DOUBLE_SLAB, LIME_CONCRETE_STAIRS),
            new VanillaSlabAndStairFamily(LIME_WOOL, LIME_WOOL_SLAB, LIME_WOOL_DOUBLE_SLAB, LIME_WOOL_STAIRS),
            new VanillaSlabAndStairFamily(MAGENTA_CONCRETE, MAGENTA_CONCRETE_SLAB, MAGENTA_CONCRETE_DOUBLE_SLAB, MAGENTA_CONCRETE_STAIRS),
            new VanillaSlabAndStairFamily(MAGENTA_WOOL, MAGENTA_WOOL_SLAB, MAGENTA_WOOL_DOUBLE_SLAB, MAGENTA_WOOL_STAIRS),
            new VanillaSlabAndStairFamily(ORANGE_CONCRETE, ORANGE_CONCRETE_SLAB, ORANGE_CONCRETE_DOUBLE_SLAB, ORANGE_CONCRETE_STAIRS),
            new VanillaSlabAndStairFamily(ORANGE_WOOL, ORANGE_WOOL_SLAB, ORANGE_WOOL_DOUBLE_SLAB, ORANGE_WOOL_STAIRS),
            new VanillaSlabAndStairFamily(PINK_CONCRETE, PINK_CONCRETE_SLAB, PINK_CONCRETE_DOUBLE_SLAB, PINK_CONCRETE_STAIRS),
            new VanillaSlabAndStairFamily(PINK_WOOL, PINK_WOOL_SLAB, PINK_WOOL_DOUBLE_SLAB, PINK_WOOL_STAIRS),
            new VanillaSlabAndStairFamily(PURPLE_CONCRETE, PURPLE_CONCRETE_SLAB, PURPLE_CONCRETE_DOUBLE_SLAB, PURPLE_CONCRETE_STAIRS),
            new VanillaSlabAndStairFamily(PURPLE_WOOL, PURPLE_WOOL_SLAB, PURPLE_WOOL_DOUBLE_SLAB, PURPLE_WOOL_STAIRS),
            new VanillaSlabAndStairFamily(RED_CONCRETE, RED_CONCRETE_SLAB, RED_CONCRETE_DOUBLE_SLAB, RED_CONCRETE_STAIRS),
            new VanillaSlabAndStairFamily(RED_WOOL, RED_WOOL_SLAB, RED_WOOL_DOUBLE_SLAB, RED_WOOL_STAIRS),
            new VanillaSlabAndStairFamily(WHITE_CONCRETE, WHITE_CONCRETE_SLAB, WHITE_CONCRETE_DOUBLE_SLAB, WHITE_CONCRETE_STAIRS),
            new VanillaSlabAndStairFamily(WHITE_WOOL, WHITE_WOOL_SLAB, WHITE_WOOL_DOUBLE_SLAB, WHITE_WOOL_STAIRS),
            new VanillaSlabAndStairFamily(YELLOW_CONCRETE, YELLOW_CONCRETE_SLAB, YELLOW_CONCRETE_DOUBLE_SLAB, YELLOW_CONCRETE_STAIRS),
            new VanillaSlabAndStairFamily(YELLOW_WOOL, YELLOW_WOOL_SLAB, YELLOW_WOOL_DOUBLE_SLAB, YELLOW_WOOL_STAIRS)
    );
}
