package org.cloudburstmc.api.boss;

import org.checkerframework.checker.nullness.qual.Nullable;
import org.cloudburstmc.api.entity.hostile.EnderDragon;
import org.cloudburstmc.api.entity.misc.EnderCrystal;
import org.cloudburstmc.api.level.Location;
import org.cloudburstmc.math.vector.Vector3i;

import java.util.Collection;
import java.util.List;

/**
 * The Ender Dragon battle associated with an End level.
 */
public interface DragonBattle {

    /**
     * Returns the dragon participating in this battle.
     *
     * @return the active dragon, or {@code null} when no dragon is alive
     */
    @Nullable
    EnderDragon getEnderDragon();

    /**
     * Returns the boss bar owned by this battle.
     *
     * @return the battle boss bar
     */
    BossBar getBossBar();

    /**
     * Returns the center of the exit portal podium.
     *
     * @return the portal location, or {@code null} before its position is known
     */
    @Nullable
    Location getEndPortalLocation();

    /**
     * Generates the exit portal podium if it is not already present.
     *
     * @param active whether to fill the portal with portal blocks
     * @return whether a podium was generated
     */
    boolean generateEndPortal(boolean active);

    /**
     * @return whether a dragon has previously been killed in this battle
     */
    boolean hasBeenPreviouslyKilled();

    /**
     * Changes whether a dragon has previously been killed in this battle.
     *
     * @param previouslyKilled whether a dragon has previously been killed
     */
    void setPreviouslyKilled(boolean previouslyKilled);

    /**
     * Attempts to begin the normal four-crystal respawn ritual.
     */
    void initiateRespawn();

    /**
     * Attempts to begin a respawn ritual using the supplied crystals.
     * An empty collection selects the four crystals placed around the exit portal.
     *
     * @param crystals the ritual crystals
     * @return whether the ritual began
     */
    boolean initiateRespawn(Collection<? extends EnderCrystal> crystals);

    /**
     * Returns the current respawn phase.
     *
     * @return the respawn phase
     */
    DragonRespawnPhase getRespawnPhase();

    /**
     * Changes the phase of an active respawn ritual.
     *
     * @param phase the new phase
     * @return whether an active ritual was updated
     */
    boolean setRespawnPhase(DragonRespawnPhase phase);

    /**
     * Clears beam targets and invulnerability from the crystals on the End spikes.
     */
    void resetCrystals();

    /**
     * Returns the number of gateways generated by this battle.
     *
     * @return the generated gateway count
     */
    int getGatewayCount();

    /**
     * Generates the next gateway selected by the battle.
     *
     * @return whether a gateway was generated
     */
    boolean spawnNewGateway();

    /**
     * Generates a gateway at a position without changing the battle's gateway count.
     *
     * @param position the gateway position
     */
    void spawnNewGateway(Vector3i position);

    /**
     * Returns an immutable snapshot of the crystals used by the current respawn ritual.
     *
     * @return the ritual crystals
     */
    List<EnderCrystal> getRespawnCrystals();

    /**
     * Returns an immutable snapshot of the crystals on the End spikes.
     *
     * @return the spike crystals
     */
    List<EnderCrystal> getHealingCrystals();
}
