package org.cloudburstmc.codegen;

import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.TypeSpec;
import lombok.experimental.UtilityClass;

import javax.lang.model.element.Modifier;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

@UtilityClass
public class BlockDataGen {

    private static final String API_BLOCK_PACKAGE = "org.cloudburstmc.api.block";
    private static final String SERVER_REGISTRY_PACKAGE = "org.cloudburstmc.server.registry";

    private static final Pattern BLOCK_TYPE_CONSTANT =
            Pattern.compile("public\\s+static\\s+final\\s+BlockType\\s+(\\w+)\\s*=");

    private static final Comparator<String> NATURAL_ORDER = (left, right) -> {
        int leftIndex = 0;
        int rightIndex = 0;

        while (leftIndex < left.length() && rightIndex < right.length()) {
            char leftChar = left.charAt(leftIndex);
            char rightChar = right.charAt(rightIndex);

            if (Character.isDigit(leftChar) && Character.isDigit(rightChar)) {
                int leftStart = leftIndex;
                int rightStart = rightIndex;
                while (leftIndex < left.length() && Character.isDigit(left.charAt(leftIndex))) {
                    leftIndex++;
                }
                while (rightIndex < right.length() && Character.isDigit(right.charAt(rightIndex))) {
                    rightIndex++;
                }
                long leftNumber = Long.parseLong(left.substring(leftStart, leftIndex));
                long rightNumber = Long.parseLong(right.substring(rightStart, rightIndex));
                if (leftNumber != rightNumber) {
                    return Long.compare(leftNumber, rightNumber);
                }
            } else {
                if (leftChar != rightChar) {
                    return Character.compare(leftChar, rightChar);
                }

                leftIndex++;
                rightIndex++;
            }
        }

        return Integer.compare(left.length() - leftIndex, right.length() - rightIndex);
    };

    static void main() throws IOException, ClassNotFoundException {
        Path projectRoot = resolveProjectRoot();
        Path blockTypes = projectRoot.resolve("api/src/main/java/org/cloudburstmc/api/block/BlockTypes.java");
        Path outputRoot = projectRoot.resolve("server/src/main/java");
        List<String> constants = parseBlockTypes(blockTypes);
        constants.sort(NATURAL_ORDER);
        JavaFile initializer = generateInitializer(constants);
        write(initializer, outputRoot);
    }

    private static List<String> parseBlockTypes(Path source) throws IOException {
        String content = Files.readString(source);
        Matcher matcher = BLOCK_TYPE_CONSTANT.matcher(content);
        List<String> constants = new ArrayList<>();
        while (matcher.find()) {
            constants.add(matcher.group(1));
        }
        if (constants.isEmpty()) {
            throw new IllegalStateException("No BlockType constants found in " + source);
        }
        return constants;
    }

    private static JavaFile generateInitializer(List<String> constants) {
        ClassName registry = ClassName.get("org.cloudburstmc.server.registry", "CloudBlockRegistry");
        TypeSpec.Builder type = TypeSpec.classBuilder("BlockTypeDefaultInitializer")
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addJavadoc("Generated by {@code BlockDataGen}, do not edit by hand.\n");
        type.addMethod(
                MethodSpec.constructorBuilder().addModifiers(Modifier.PRIVATE).build());
        MethodSpec.Builder init = MethodSpec.methodBuilder("init")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .addParameter(registry, "registry");
        for (String constant : constants) {
            init.addStatement("registry.registerVanilla($L)", constant);
        }
        type.addMethod(init.build());
        return JavaFile.builder("org.cloudburstmc.server.registry", type.build())
                .addStaticImport(ClassName.get("org.cloudburstmc.api.block", "BlockTypes"), "*")
                .skipJavaLangImports(true)
                .indent("    ")
                .build();
    }

    private static void write(JavaFile javaFile, Path outputRoot) throws IOException {
        Path output = outputRoot
                .resolve(SERVER_REGISTRY_PACKAGE.replace('.', '/'))
                .resolve("BlockTypeDefaultInitializer.java");
        Files.createDirectories(output.getParent());
        Files.writeString(output, javaFile.toString());
    }

    private static Path resolveProjectRoot() {
        Path directory = Paths.get(System.getProperty("user.dir")).toAbsolutePath();
        while (directory != null) {
            if (Files.exists(directory.resolve("settings.gradle.kts"))) {
                return directory;
            }
            directory = directory.getParent();
        }
        throw new IllegalStateException("Could not locate project root (no settings.gradle.kts found)");
    }
}
