package org.cloudburstmc.codegen;

import com.palantir.javapoet.*;
import lombok.experimental.UtilityClass;
import tools.jackson.core.type.TypeReference;
import tools.jackson.databind.ObjectMapper;

import javax.lang.model.element.Modifier;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

@UtilityClass
public class ItemDataGen {

    private static final String API_ITEM_PACKAGE = "org.cloudburstmc.api.item";
    private static final String API_UTIL_PACKAGE = "org.cloudburstmc.api.util";

    private static final Pattern IDENTIFIER_CONSTANT = Pattern.compile(
            "public\\s+static\\s+final\\s+Identifier\\s+(\\w+)\\s*=\\s*Identifier\\.parse\\(\"([^\"]+)\"\\)");
    private static final Comparator<String> NATURAL_ORDER = (left, right) -> {
        int leftIdx = 0;
        int rightIdx = 0;

        while (leftIdx < left.length() && rightIdx < right.length()) {
            char leftChar = left.charAt(leftIdx), rightChar = right.charAt(rightIdx);
            if (Character.isDigit(leftChar) && Character.isDigit(rightChar)) {
                int leftNumStart = leftIdx, rightNumStart = rightIdx;

                while (leftIdx < left.length() && Character.isDigit(left.charAt(leftIdx))) {
                    leftIdx++;
                }

                while (rightIdx < right.length() && Character.isDigit(right.charAt(rightIdx))) {
                    rightIdx++;
                }

                long leftNum = Long.parseLong(left.substring(leftNumStart, leftIdx));
                long rightNum = Long.parseLong(right.substring(rightNumStart, rightIdx));

                if (leftNum != rightNum) {
                    return Long.compare(leftNum, rightNum);
                }
            } else {
                if (leftChar != rightChar) {
                    return Character.compare(leftChar, rightChar);
                }

                leftIdx++;
                rightIdx++;
            }
        }

        return Integer.compare(left.length() - leftIdx, right.length() - rightIdx);
    };

    static void main() throws IOException {
        Path projectRoot = resolveProjectRoot();
        Path outputRoot = projectRoot.resolve("api/src/main/java");

        GenerationResult result = generate(projectRoot);
        Files.createDirectories(outputRoot);
        writeCompact(result.itemTypes(), outputRoot, "ItemTypes.java");
    }

    private static GenerationResult generate(Path projectRoot) throws IOException {
        Path dataDir = projectRoot.resolve("server/src/main/resources/data");
        RuntimeItems runtimeItems = loadRuntimeItems(dataDir.resolve("runtime_item_states.json"));
        Set<String> mappedAliasIdentifiers = loadMappedAliasIdentifiers(dataDir.resolve("item_mappings.json"));

        List<ItemConstant> allIdConstants = buildItemConstants(runtimeItems.identifiers());
        List<ItemConstant> idConstants = new ArrayList<>(allIdConstants.stream()
                .filter(item -> !mappedAliasIdentifiers.contains(item.identifier()))
                .toList());
        idConstants.sort(Comparator.comparing(ItemConstant::constantName, NATURAL_ORDER));

        return new GenerationResult(
                generateItemTypes(idConstants));
    }

    private static JavaFile generateItemTypes(List<ItemConstant> constants) {
        ClassName utilityClass = ClassName.get("lombok.experimental", "UtilityClass");
        ClassName field = ClassName.get(java.lang.reflect.Field.class);
        ClassName linkedHashMap = ClassName.get(LinkedHashMap.class);
        ClassName map = ClassName.get(Map.class);
        ClassName objects = ClassName.get(Objects.class);
        ClassName optional = ClassName.get(Optional.class);
        ClassName identifier = ClassName.get(API_UTIL_PACKAGE, "Identifier");
        ClassName itemType = ClassName.get(API_ITEM_PACKAGE, "ItemType");

        TypeSpec.Builder type = TypeSpec.classBuilder("ItemTypes")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(utilityClass)
                .addJavadoc("Generated by {@code ItemDataGen}, do not edit by hand.\n");

        for (ItemConstant constant : constants) {
            type.addField(FieldSpec.builder(itemType, constant.constantName(), Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                    .initializer("$T.of($T.parse($S))", itemType, identifier, constant.identifier())
                    .build());
        }

        type.addField(FieldSpec.builder(itemType, "UNKNOWN", Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                .initializer("$T.of($T.parse($S))", itemType, identifier, "unknown")
                .build());

        type.addMethod(MethodSpec.methodBuilder("get")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .returns(ParameterizedTypeName.get(optional, itemType))
                .addParameter(identifier, "id")
                .addJavadoc("Returns the generated item type constant with the supplied identifier.\n\n")
                .addJavadoc("@param id item identifier\n")
                .addJavadoc("@return matching generated item type constant, if present\n")
                .addStatement("$T.requireNonNull(id, $S)", objects, "id")
                .addStatement("return $T.ofNullable(Lookup.VALUES.get(id))", optional)
                .build());

        TypeName lookupMap = ParameterizedTypeName.get(map, identifier, itemType);
        type.addType(TypeSpec.classBuilder("Lookup")
                .addModifiers(Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
                .addField(FieldSpec.builder(lookupMap, "VALUES", Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
                        .initializer("create()")
                        .build())
                .addMethod(MethodSpec.methodBuilder("create")
                        .addModifiers(Modifier.PRIVATE, Modifier.STATIC)
                        .returns(lookupMap)
                        .addStatement("$T values = new $T<>()", lookupMap, linkedHashMap)
                        .beginControlFlow("for ($T field : ItemTypes.class.getFields())", field)
                        .beginControlFlow("if (field.getType() != $T.class)", itemType)
                        .addStatement("continue")
                        .endControlFlow()
                        .beginControlFlow("try")
                        .addStatement("$T type = ($T) field.get(null)", itemType, itemType)
                        .addStatement("values.put(type.getId(), type)")
                        .nextControlFlow("catch ($T e)", IllegalAccessException.class)
                        .addStatement("throw new $T($S + field.getName(), e)", IllegalStateException.class, "Unable to read item type field ")
                        .endControlFlow()
                        .endControlFlow()
                        .addStatement("return $T.copyOf(values)", map)
                        .build())
                .build());

        return JavaFile.builder(API_ITEM_PACKAGE, type.build())
                .skipJavaLangImports(true)
                .indent("    ")
                .build();
    }

    private static void writeCompact(JavaFile javaFile, Path outputRoot, String fileName) throws IOException {
        Path output = outputRoot.resolve(API_ITEM_PACKAGE.replace('.', '/')).resolve(fileName);
        Files.createDirectories(output.getParent());
        Files.writeString(output, compactGeneratedSource(javaFile.toString()));
    }

    private static String compactGeneratedSource(String source) {
        return source.replace("\r\n", "\n")
                .replaceAll("\n\n(    public static final )", "\n$1")
                .replaceAll("\n(    public static final \\w+ UNKNOWN )", "\n\n$1");
    }

    private static RuntimeItems loadRuntimeItems(Path runtimeItemStates) throws IOException {
        List<Map<String, Object>> data = new ObjectMapper().readValue(runtimeItemStates.toFile(), new TypeReference<>() {});
        List<String> identifiers = new ArrayList<>();
        Set<String> seen = new HashSet<>();

        for (Map<String, Object> entry : data) {
            String identifier = stripNamespace(entry.get("name").toString());
            if ("unknown".equals(identifier) || seen.contains(identifier)) {
                continue;
            }

            if (identifier.startsWith("item.")) {
                continue;
            }

            seen.add(identifier);
            identifiers.add(identifier);
        }

        return new RuntimeItems(identifiers);
    }

    private static Set<String> loadMappedAliasIdentifiers(Path itemMappings) throws IOException {
        Map<String, Object> data = new ObjectMapper().readValue(itemMappings.toFile(), new TypeReference<>() {});
        Set<String> aliases = new HashSet<>();
        Object simple = data.get("simple");
        if (simple instanceof Map<?, ?> simpleMap) {
            for (Object identifier : simpleMap.keySet()) {
                aliases.add(stripNamespace(identifier.toString()));
            }
        }

        Object complex = data.get("complex");
        if (complex instanceof Map<?, ?> complexMap) {
            for (Map.Entry<?, ?> entry : complexMap.entrySet()) {
                String identifier = stripNamespace(entry.getKey().toString());
                if (entry.getValue() instanceof Map<?, ?> metaMap) {
                    Object metaZero = metaMap.get("0");
                    if (metaZero != null && !identifier.equals(stripNamespace(metaZero.toString()))) {
                        aliases.add(identifier);
                    }
                }
            }
        }

        return aliases;
    }

    private static Map<String, String> parseIdentifierConstants(Path source) throws IOException {
        Map<String, String> identifiers = new LinkedHashMap<>();
        Matcher matcher = IDENTIFIER_CONSTANT.matcher(Files.readString(source));
        while (matcher.find()) {
            identifiers.put(matcher.group(2), matcher.group(1));
        }

        return identifiers;
    }

    private static List<ItemConstant> buildItemConstants(List<String> identifiers) {
        List<ItemConstant> constants = new ArrayList<>();
        Map<String, String> identifiersByConstant = new HashMap<>();

        for (String identifier : identifiers) {
            String constant = constantName(identifier);
            String existing = identifiersByConstant.putIfAbsent(constant, identifier);
            if (existing != null && !existing.equals(identifier)) {
                throw new IllegalStateException("'" + identifier + "' and '" + existing + "' both map to ItemTypes." + constant);
            }
            constants.add(new ItemConstant(constant, identifier));
        }

        return constants;
    }

    private static String stripNamespace(String identifier) {
        int colon = identifier.indexOf(':');
        if (colon < 0) {
            return identifier;
        }

        String namespace = identifier.substring(0, colon);
        if (!"minecraft".equals(namespace)) {
            throw new IllegalArgumentException("Unsupported item namespace '" + namespace + "' in '" + identifier + "'");
        }

        return identifier.substring(colon + 1);
    }

    private static String constantName(String identifier) {
        String name = identifier.replaceAll("[^0-9A-Za-z]+", "_")
                .replaceAll("^_+", "")
                .replaceAll("_+$", "")
                .toUpperCase(Locale.ROOT);
        if (name.isEmpty()) {
            throw new IllegalArgumentException("Cannot derive a Java constant from '" + identifier + "'");
        }

        if (Character.isDigit(name.charAt(0))) {
            name = "_" + name;
        }

        return name;
    }

    private static Path resolveProjectRoot() {
        Path dir = Paths.get(System.getProperty("user.dir")).toAbsolutePath();
        while (dir != null) {
            if (Files.exists(dir.resolve("settings.gradle.kts"))) {
                return dir;
            }

            dir = dir.getParent();
        }
        throw new IllegalStateException("Could not locate project root (no settings.gradle.kts found)");
    }

    private record RuntimeItems(List<String> identifiers) {
    }

    private record ItemConstant(String constantName, String identifier) {
    }

    private record GenerationResult(JavaFile itemTypes) {
    }
}
