package org.cloudburstmc.codegen;

import lombok.experimental.UtilityClass;
import tools.jackson.core.type.TypeReference;
import tools.jackson.databind.ObjectMapper;

import java.io.IOException;
import java.nio.file.Path;
import java.util.*;

import static org.cloudburstmc.codegen.DataGenSupport.*;

@UtilityClass
public class ItemDataGen {

    private static final Path ITEM_TYPES_PATH = Path.of("org", "cloudburstmc", "api", "item", "ItemTypes.java");
    private static final Path ITEM_DEFINITION_COMPONENTS_PATH = Path.of("org", "cloudburstmc", "api", "item", "ItemDefinitionComponents.java");

    public static void generate() throws IOException {
        Path projectRoot = resolveProjectRoot();
        Path outputRoot = projectRoot.resolve("api/src/main/java");

        writeSource(outputRoot.resolve(ITEM_TYPES_PATH), generateItemTypes(projectRoot));
        writeSource(outputRoot.resolve(ITEM_DEFINITION_COMPONENTS_PATH), generateItemDefinitionComponents());
    }

    private static String generateItemTypes(Path projectRoot) {
        Path dataDir = projectRoot.resolve("server/src/main/resources/data");
        RuntimeItems runtimeItems = loadRuntimeItems(dataDir.resolve("runtime_item_states.json"));
        Set<String> mappedAliasIdentifiers = loadMappedAliasIdentifiers(dataDir.resolve("item_mappings.json"));

        List<DataGenSupport.GeneratedConstant> allIdConstants = constants(runtimeItems.identifiers());
        List<DataGenSupport.GeneratedConstant> idConstants = new ArrayList<>(allIdConstants.stream()
                .filter(item -> !mappedAliasIdentifiers.contains(item.identifier()))
                .toList());

        return renderItemTypes(idConstants);
    }

    private static String renderItemTypes(List<DataGenSupport.GeneratedConstant> constants) {
        StringBuilder source = new StringBuilder();
        source.append("""
                package org.cloudburstmc.api.item;
                
                import lombok.experimental.UtilityClass;
                import org.cloudburstmc.api.internal.BuiltInTypeCatalog;
                import org.cloudburstmc.api.util.Identifier;
                
                import java.util.List;
                import java.util.Optional;
                
                /**
                 * Generated by {@code ItemDataGen}, do not edit by hand.
                 */
                @UtilityClass
                public class ItemTypes {
                    private static final BuiltInTypeCatalog<ItemType> TYPES = BuiltInTypeCatalog.create(ItemType::getId);
                
                """);

        for (DataGenSupport.GeneratedConstant constant : constants) {
            source.append("    public static final ItemType ")
                    .append(constant.name())
                    .append(" = type(\"")
                    .append(constant.identifier())
                    .append("\");\n");
        }

        source.append("""
                
                    public static final ItemType UNKNOWN = type("unknown");
                
                    /**
                     * Returns the built-in item type with the supplied identifier.
                     *
                     * @param id item identifier
                     * @return matching built-in item type, if present
                     */
                    public static Optional<ItemType> get(Identifier id) {
                        return TYPES.get(id);
                    }
                
                    /**
                     * Returns all built-in item types in declaration order.
                     *
                     * @return built-in item types
                     */
                    public static List<ItemType> values() {
                        return TYPES.values();
                    }
                
                    private static ItemType type(String id) {
                        return TYPES.register(ItemType.of(Identifier.parse(id)));
                    }
                }
                """);
        return source.toString();
    }

    private static String generateItemDefinitionComponents() throws IOException {
        List<String> identifiers = loadComponentIdentifiers("item_definition_components.json");

        Set<String> seenIdentifiers = new HashSet<>();
        Map<String, String> identifiersByConstant = new HashMap<>();
        for (String identifier : identifiers) {
            if (!seenIdentifiers.add(identifier)) {
                throw new IOException("Duplicate item-definition component '" + identifier + "'");
            }

            String constant = constantName(stripMinecraftNamespace(identifier));
            String existing = identifiersByConstant.putIfAbsent(constant, identifier);
            if (existing != null) {
                throw new IOException("'" + identifier + "' and '" + existing + "' both map to ItemDefinitionComponents." + constant);
            }
        }

        StringBuilder source = new StringBuilder();
        source.append("""
                package org.cloudburstmc.api.item;
                
                import lombok.experimental.UtilityClass;
                import org.cloudburstmc.api.internal.BuiltInTypeCatalog;
                import org.cloudburstmc.api.util.Identifier;
                
                import java.util.List;
                import java.util.Optional;
                
                /**
                 * Generated by {@code ItemDataGen}, do not edit by hand.
                 */
                @UtilityClass
                public class ItemDefinitionComponents {
                    private static final BuiltInTypeCatalog<ItemDefinitionComponentType> TYPES = BuiltInTypeCatalog.create(ItemDefinitionComponentType::getId);
                
                """);

        for (String identifier : identifiers) {
            source.append("    public static final ItemDefinitionComponentType ")
                    .append(constantName(stripMinecraftNamespace(identifier)))
                    .append(" = type(\"")
                    .append(identifier)
                    .append("\");\n");
        }

        source.append("""
                
                    /**
                     * Returns a built-in item-definition component type.
                     *
                     * @param id component identifier
                     * @return matching component type, if present
                     */
                    public static Optional<ItemDefinitionComponentType> get(Identifier id) {
                        return TYPES.get(id);
                    }
                
                    /**
                     * Returns all built-in item-definition component types.
                     *
                     * @return component types in declaration order
                     */
                    public static List<ItemDefinitionComponentType> values() {
                        return TYPES.values();
                    }
                
                    private static ItemDefinitionComponentType type(String id) {
                        return TYPES.register(ItemDefinitionComponentType.builtIn(Identifier.parse(id)));
                    }
                }
                """);
        return source.toString();
    }

    private static RuntimeItems loadRuntimeItems(Path runtimeItemStates) {
        List<Map<String, Object>> data = new ObjectMapper().readValue(runtimeItemStates.toFile(), new TypeReference<>() {});
        List<String> identifiers = new ArrayList<>();
        Set<String> seen = new HashSet<>();

        for (Map<String, Object> entry : data) {
            String identifier = stripMinecraftNamespace(entry.get("name").toString());
            if ("unknown".equals(identifier) || seen.contains(identifier)) {
                continue;
            }

            if (identifier.startsWith("item.")) {
                continue;
            }

            seen.add(identifier);
            identifiers.add(identifier);
        }

        return new RuntimeItems(identifiers);
    }

    private static Set<String> loadMappedAliasIdentifiers(Path itemMappings) {
        Map<String, Object> data = new ObjectMapper().readValue(itemMappings.toFile(), new TypeReference<>() {
        });
        Set<String> aliases = new HashSet<>();
        Object simple = data.get("simple");
        if (simple instanceof Map<?, ?> simpleMap) {
            for (Object identifier : simpleMap.keySet()) {
                aliases.add(stripMinecraftNamespace(identifier.toString()));
            }
        }

        Object complex = data.get("complex");
        if (complex instanceof Map<?, ?> complexMap) {
            for (Map.Entry<?, ?> entry : complexMap.entrySet()) {
                String identifier = stripMinecraftNamespace(entry.getKey().toString());
                if (entry.getValue() instanceof Map<?, ?> metaMap) {
                    Object metaZero = metaMap.get("0");
                    if (metaZero != null && !identifier.equals(stripMinecraftNamespace(metaZero.toString()))) {
                        aliases.add(identifier);
                    }
                }
            }
        }

        return aliases;
    }

    private record RuntimeItems(List<String> identifiers) {
    }

}
