package org.cloudburstmc.codegen;

import lombok.experimental.UtilityClass;
import tools.jackson.core.type.TypeReference;
import tools.jackson.databind.ObjectMapper;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.*;

@UtilityClass
public class ItemDataGen {

    private static final Path ITEM_TYPES_PATH = Path.of(
            "org", "cloudburstmc", "api", "item", "ItemTypes.java");
    private static final Comparator<String> NATURAL_ORDER = (left, right) -> {
        int leftIdx = 0;
        int rightIdx = 0;

        while (leftIdx < left.length() && rightIdx < right.length()) {
            char leftChar = left.charAt(leftIdx), rightChar = right.charAt(rightIdx);
            if (Character.isDigit(leftChar) && Character.isDigit(rightChar)) {
                int leftNumStart = leftIdx, rightNumStart = rightIdx;

                while (leftIdx < left.length() && Character.isDigit(left.charAt(leftIdx))) {
                    leftIdx++;
                }

                while (rightIdx < right.length() && Character.isDigit(right.charAt(rightIdx))) {
                    rightIdx++;
                }

                long leftNum = Long.parseLong(left.substring(leftNumStart, leftIdx));
                long rightNum = Long.parseLong(right.substring(rightNumStart, rightIdx));

                if (leftNum != rightNum) {
                    return Long.compare(leftNum, rightNum);
                }
            } else {
                if (leftChar != rightChar) {
                    return Character.compare(leftChar, rightChar);
                }

                leftIdx++;
                rightIdx++;
            }
        }

        return Integer.compare(left.length() - leftIdx, right.length() - rightIdx);
    };

    public static void main() throws IOException {
        Path projectRoot = resolveProjectRoot();
        Path outputRoot = projectRoot.resolve("api/src/main/java");

        writeItemTypes(generate(projectRoot), outputRoot);
    }

    private static String generate(Path projectRoot) throws IOException {
        Path dataDir = projectRoot.resolve("server/src/main/resources/data");
        RuntimeItems runtimeItems = loadRuntimeItems(dataDir.resolve("runtime_item_states.json"));
        Set<String> mappedAliasIdentifiers = loadMappedAliasIdentifiers(dataDir.resolve("item_mappings.json"));

        List<ItemConstant> allIdConstants = buildItemConstants(runtimeItems.identifiers());
        List<ItemConstant> idConstants = new ArrayList<>(allIdConstants.stream()
                .filter(item -> !mappedAliasIdentifiers.contains(item.identifier()))
                .toList());
        idConstants.sort(Comparator.comparing(ItemConstant::constantName, NATURAL_ORDER));

        return generateItemTypes(idConstants);
    }

    private static String generateItemTypes(List<ItemConstant> constants) {
        StringBuilder source = new StringBuilder();
        source.append("""
                package org.cloudburstmc.api.item;
                
                import lombok.experimental.UtilityClass;
                import org.cloudburstmc.api.util.Identifier;
                
                import java.lang.reflect.Field;
                import java.util.*;
                
                /**
                 * Generated by {@code ItemDataGen}, do not edit by hand.
                 */
                @UtilityClass
                public class ItemTypes {
                """);
        for (ItemConstant constant : constants) {
            source.append("    public static final ItemType ")
                    .append(constant.constantName())
                    .append(" = ItemType.of(Identifier.parse(\"")
                    .append(constant.identifier())
                    .append("\"));\n");
        }

        source.append("""
                
                    public static final ItemType UNKNOWN = ItemType.of(Identifier.parse("unknown"));
                
                    /**
                     * Returns the generated item type constant with the supplied identifier.
                     *
                     * @param id item identifier
                     * @return matching generated item type constant, if present
                     */
                    public static Optional<ItemType> get(Identifier id) {
                        Objects.requireNonNull(id, "id");
                        return Optional.ofNullable(Lookup.VALUES.get(id));
                    }
                
                    /**
                     * Returns all generated item type constants in declaration order.
                     *
                     * @return generated item type constants
                     */
                    public static Collection<ItemType> values() {
                        return Lookup.VALUES.values();
                    }
                
                    private static final class Lookup {
                        private static final Map<Identifier, ItemType> VALUES = create();
                
                        private static Map<Identifier, ItemType> create() {
                            Map<Identifier, ItemType> values = new LinkedHashMap<>();
                            for (Field field : ItemTypes.class.getFields()) {
                                if (field.getType() != ItemType.class) {
                                    continue;
                                }
                                try {
                                    ItemType type = (ItemType) field.get(null);
                                    values.put(type.getId(), type);
                                } catch (IllegalAccessException e) {
                                    throw new IllegalStateException("Unable to read item type field " + field.getName(), e);
                                }
                            }
                            return Collections.unmodifiableMap(values);
                        }
                    }
                }
                """);
        return source.toString();
    }

    private static void writeItemTypes(String source, Path outputRoot) throws IOException {
        Path output = outputRoot.resolve(ITEM_TYPES_PATH);
        Files.createDirectories(output.getParent());
        Files.writeString(output, source.replace("\r\n", "\n"));
    }

    private static RuntimeItems loadRuntimeItems(Path runtimeItemStates) throws IOException {
        List<Map<String, Object>> data = new ObjectMapper().readValue(runtimeItemStates.toFile(), new TypeReference<>() {});
        List<String> identifiers = new ArrayList<>();
        Set<String> seen = new HashSet<>();

        for (Map<String, Object> entry : data) {
            String identifier = stripNamespace(entry.get("name").toString());
            if ("unknown".equals(identifier) || seen.contains(identifier)) {
                continue;
            }

            if (identifier.startsWith("item.")) {
                continue;
            }

            seen.add(identifier);
            identifiers.add(identifier);
        }

        return new RuntimeItems(identifiers);
    }

    private static Set<String> loadMappedAliasIdentifiers(Path itemMappings) throws IOException {
        Map<String, Object> data = new ObjectMapper().readValue(itemMappings.toFile(), new TypeReference<>() {});
        Set<String> aliases = new HashSet<>();
        Object simple = data.get("simple");
        if (simple instanceof Map<?, ?> simpleMap) {
            for (Object identifier : simpleMap.keySet()) {
                aliases.add(stripNamespace(identifier.toString()));
            }
        }

        Object complex = data.get("complex");
        if (complex instanceof Map<?, ?> complexMap) {
            for (Map.Entry<?, ?> entry : complexMap.entrySet()) {
                String identifier = stripNamespace(entry.getKey().toString());
                if (entry.getValue() instanceof Map<?, ?> metaMap) {
                    Object metaZero = metaMap.get("0");
                    if (metaZero != null && !identifier.equals(stripNamespace(metaZero.toString()))) {
                        aliases.add(identifier);
                    }
                }
            }
        }

        return aliases;
    }

    private static List<ItemConstant> buildItemConstants(List<String> identifiers) {
        List<ItemConstant> constants = new ArrayList<>();
        Map<String, String> identifiersByConstant = new HashMap<>();

        for (String identifier : identifiers) {
            String constant = constantName(identifier);
            String existing = identifiersByConstant.putIfAbsent(constant, identifier);
            if (existing != null && !existing.equals(identifier)) {
                throw new IllegalStateException("'" + identifier + "' and '" + existing + "' both map to ItemTypes." + constant);
            }
            constants.add(new ItemConstant(constant, identifier));
        }

        return constants;
    }

    private static String stripNamespace(String identifier) {
        int colon = identifier.indexOf(':');
        if (colon < 0) {
            return identifier;
        }

        String namespace = identifier.substring(0, colon);
        if (!"minecraft".equals(namespace)) {
            throw new IllegalArgumentException("Unsupported item namespace '" + namespace + "' in '" + identifier + "'");
        }

        return identifier.substring(colon + 1);
    }

    private static String constantName(String identifier) {
        String name = identifier.replaceAll("[^0-9A-Za-z]+", "_")
                .replaceAll("^_+", "")
                .replaceAll("_+$", "")
                .toUpperCase(Locale.ROOT);
        if (name.isEmpty()) {
            throw new IllegalArgumentException("Cannot derive a Java constant from '" + identifier + "'");
        }

        if (Character.isDigit(name.charAt(0))) {
            name = "_" + name;
        }

        return name;
    }

    private static Path resolveProjectRoot() {
        Path dir = Paths.get(System.getProperty("user.dir")).toAbsolutePath();
        while (dir != null) {
            if (Files.exists(dir.resolve("settings.gradle.kts"))) {
                return dir;
            }

            dir = dir.getParent();
        }
        throw new IllegalStateException("Could not locate project root (no settings.gradle.kts found)");
    }

    private record RuntimeItems(List<String> identifiers) {
    }

    private record ItemConstant(String constantName, String identifier) {
    }

}
