package org.cloudburstmc.server.level.biome;

import lombok.experimental.UtilityClass;
import org.cloudburstmc.api.util.Identifier;

@UtilityClass
public class BiomeIds {
    //sorted by legacy ID
    public static final Identifier OCEAN = Identifier.parse("ocean");
    public static final Identifier PLAINS = Identifier.parse("plains");
    public static final Identifier DESERT = Identifier.parse("desert");
    public static final Identifier EXTREME_HILLS = Identifier.parse("extreme_hills");
    public static final Identifier FOREST = Identifier.parse("forest");
    public static final Identifier TAIGA = Identifier.parse("taiga");
    public static final Identifier SWAMPLAND = Identifier.parse("swampland");
    public static final Identifier RIVER = Identifier.parse("river");
    public static final Identifier HELL = Identifier.parse("hell");
    public static final Identifier THE_END = Identifier.parse("the_end");
    public static final Identifier LEGACY_FROZEN_OCEAN = Identifier.parse("legacy_frozen_ocean");
    public static final Identifier FROZEN_RIVER = Identifier.parse("frozen_river");
    public static final Identifier ICE_PLAINS = Identifier.parse("ice_plains");
    public static final Identifier ICE_MOUNTAINS = Identifier.parse("ice_mountains");
    public static final Identifier MUSHROOM_ISLAND = Identifier.parse("mushroom_island");
    public static final Identifier MUSHROOM_ISLAND_SHORE = Identifier.parse("mushroom_island_shore");
    public static final Identifier BEACH = Identifier.parse("beach");
    public static final Identifier DESERT_HILLS = Identifier.parse("desert_hills");
    public static final Identifier FOREST_HILLS = Identifier.parse("forest_hills");
    public static final Identifier TAIGA_HILLS = Identifier.parse("taiga_hills");
    public static final Identifier EXTREME_HILLS_EDGE = Identifier.parse("extreme_hills_edge");
    public static final Identifier JUNGLE = Identifier.parse("jungle");
    public static final Identifier JUNGLE_HILLS = Identifier.parse("jungle_hills");
    public static final Identifier JUNGLE_EDGE = Identifier.parse("jungle_edge");
    public static final Identifier DEEP_OCEAN = Identifier.parse("deep_ocean");
    public static final Identifier STONE_BEACH = Identifier.parse("stone_beach");
    public static final Identifier COLD_BEACH = Identifier.parse("cold_beach");
    public static final Identifier BIRCH_FOREST = Identifier.parse("birch_forest");
    public static final Identifier BIRCH_FOREST_HILLS = Identifier.parse("birch_forest_hills");
    public static final Identifier ROOFED_FOREST = Identifier.parse("roofed_forest");
    public static final Identifier COLD_TAIGA = Identifier.parse("cold_taiga");
    public static final Identifier COLD_TAIGA_HILLS = Identifier.parse("cold_taiga_hills");
    public static final Identifier MEGA_TAIGA = Identifier.parse("mega_taiga");
    public static final Identifier MEGA_TAIGA_HILLS = Identifier.parse("mega_taiga_hills");
    public static final Identifier EXTREME_HILLS_PLUS_TREES = Identifier.parse("extreme_hills_plus_trees");
    public static final Identifier SAVANNA = Identifier.parse("savanna");
    public static final Identifier SAVANNA_PLATEAU = Identifier.parse("savanna_plateau");
    public static final Identifier MESA = Identifier.parse("mesa");
    public static final Identifier MESA_PLATEAU_STONE = Identifier.parse("mesa_plateau_stone");
    public static final Identifier MESA_PLATEAU = Identifier.parse("mesa_plateau");
    public static final Identifier WARM_OCEAN = Identifier.parse("warm_ocean");
    public static final Identifier DEEP_WARM_OCEAN = Identifier.parse("deep_warm_ocean");
    public static final Identifier LUKEWARM_OCEAN = Identifier.parse("lukewarm_ocean");
    public static final Identifier DEEP_LUKEWARM_OCEAN = Identifier.parse("deep_lukewarm_ocean");
    public static final Identifier COLD_OCEAN = Identifier.parse("cold_ocean");
    public static final Identifier DEEP_COLD_OCEAN = Identifier.parse("deep_cold_ocean");
    public static final Identifier FROZEN_OCEAN = Identifier.parse("frozen_ocean");
    public static final Identifier DEEP_FROZEN_OCEAN = Identifier.parse("deep_frozen_ocean");
    public static final Identifier BAMBOO_JUNGLE = Identifier.parse("bamboo_jungle");
    public static final Identifier BAMBOO_JUNGLE_HILLS = Identifier.parse("bamboo_jungle_hills");
    public static final Identifier SUNFLOWER_PLAINS = Identifier.parse("sunflower_plains");
    public static final Identifier DESERT_MUTATED = Identifier.parse("desert_mutated");
    public static final Identifier EXTREME_HILLS_MUTATED = Identifier.parse("extreme_hills_mutated");
    public static final Identifier FLOWER_FOREST = Identifier.parse("flower_forest");
    public static final Identifier TAIGA_MUTATED = Identifier.parse("taiga_mutated");
    public static final Identifier SWAMPLAND_MUTATED = Identifier.parse("swampland_mutated");
    public static final Identifier ICE_PLAINS_SPIKES = Identifier.parse("ice_plains_spikes");
    public static final Identifier JUNGLE_MUTATED = Identifier.parse("jungle_mutated");
    public static final Identifier JUNGLE_EDGE_MUTATED = Identifier.parse("jungle_edge_mutated");
    public static final Identifier BIRCH_FOREST_MUTATED = Identifier.parse("birch_forest_mutated");
    public static final Identifier BIRCH_FOREST_HILLS_MUTATED = Identifier.parse("birch_forest_hills_mutated");
    public static final Identifier ROOFED_FOREST_MUTATED = Identifier.parse("roofed_forest_mutated");
    public static final Identifier COLD_TAIGA_MUTATED = Identifier.parse("cold_taiga_mutated");
    public static final Identifier REDWOOD_TAIGA_MUTATED = Identifier.parse("redwood_taiga_mutated");
    public static final Identifier REDWOOD_TAIGA_HILLS_MUTATED = Identifier.parse("redwood_taiga_hills_mutated");
    public static final Identifier EXTREME_HILLS_PLUS_TREES_MUTATED = Identifier.parse("extreme_hills_plus_trees_mutated");
    public static final Identifier SAVANNA_MUTATED = Identifier.parse("savanna_mutated");
    public static final Identifier SAVANNA_PLATEAU_MUTATED = Identifier.parse("savanna_plateau_mutated");
    public static final Identifier MESA_BRYCE = Identifier.parse("mesa_bryce");
    public static final Identifier MESA_PLATEAU_STONE_MUTATED = Identifier.parse("mesa_plateau_stone_mutated");
    public static final Identifier MESA_PLATEAU_MUTATED = Identifier.parse("mesa_plateau_mutated");
}
