package org.cloudburstmc.api.item;

import lombok.experimental.UtilityClass;
import org.cloudburstmc.api.internal.BuiltInTypeCatalog;
import org.cloudburstmc.api.util.Identifier;

import java.util.List;
import java.util.Optional;

/**
 * Generated by {@code ItemDataGen}, do not edit by hand.
 */
@UtilityClass
public class ItemDefinitionComponents {
    private static final BuiltInTypeCatalog<ItemDefinitionComponentType> TYPES = BuiltInTypeCatalog.create(ItemDefinitionComponentType::getId);

    public static final ItemDefinitionComponentType ALLOW_OFF_HAND = type("minecraft:allow_off_hand");
    public static final ItemDefinitionComponentType BLOCK_PLACER = type("minecraft:block_placer");
    public static final ItemDefinitionComponentType BUNDLE_INTERACTION = type("minecraft:bundle_interaction");
    public static final ItemDefinitionComponentType CAN_DESTROY_IN_CREATIVE = type("minecraft:can_destroy_in_creative");
    public static final ItemDefinitionComponentType COMPOSTABLE = type("minecraft:compostable");
    public static final ItemDefinitionComponentType COOLDOWN = type("minecraft:cooldown");
    public static final ItemDefinitionComponentType DAMAGE = type("minecraft:damage");
    public static final ItemDefinitionComponentType DAMAGE_ABSORPTION = type("minecraft:damage_absorption");
    public static final ItemDefinitionComponentType DIGGER = type("minecraft:digger");
    public static final ItemDefinitionComponentType DISPLAY_NAME = type("minecraft:display_name");
    public static final ItemDefinitionComponentType DURABILITY = type("minecraft:durability");
    public static final ItemDefinitionComponentType DURABILITY_SENSOR = type("minecraft:durability_sensor");
    public static final ItemDefinitionComponentType DYEABLE = type("minecraft:dyeable");
    public static final ItemDefinitionComponentType ENCHANTABLE = type("minecraft:enchantable");
    public static final ItemDefinitionComponentType ENTITY_PLACER = type("minecraft:entity_placer");
    public static final ItemDefinitionComponentType FIRE_RESISTANT = type("minecraft:fire_resistant");
    public static final ItemDefinitionComponentType FOOD = type("minecraft:food");
    public static final ItemDefinitionComponentType FUEL = type("minecraft:fuel");
    public static final ItemDefinitionComponentType GLINT = type("minecraft:glint");
    public static final ItemDefinitionComponentType HAND_EQUIPPED = type("minecraft:hand_equipped");
    public static final ItemDefinitionComponentType HOVER_TEXT_COLOR = type("minecraft:hover_text_color");
    public static final ItemDefinitionComponentType ICON = type("minecraft:icon");
    public static final ItemDefinitionComponentType INTERACT_BUTTON = type("minecraft:interact_button");
    public static final ItemDefinitionComponentType KINETIC_WEAPON = type("minecraft:kinetic_weapon");
    public static final ItemDefinitionComponentType LIQUID_CLIPPED = type("minecraft:liquid_clipped");
    public static final ItemDefinitionComponentType MAX_STACK_SIZE = type("minecraft:max_stack_size");
    public static final ItemDefinitionComponentType PIERCING_WEAPON = type("minecraft:piercing_weapon");
    public static final ItemDefinitionComponentType PROJECTILE = type("minecraft:projectile");
    public static final ItemDefinitionComponentType RARITY = type("minecraft:rarity");
    public static final ItemDefinitionComponentType RECORD = type("minecraft:record");
    public static final ItemDefinitionComponentType REPAIRABLE = type("minecraft:repairable");
    public static final ItemDefinitionComponentType SHOOTER = type("minecraft:shooter");
    public static final ItemDefinitionComponentType SHOULD_DESPAWN = type("minecraft:should_despawn");
    public static final ItemDefinitionComponentType STACKED_BY_DATA = type("minecraft:stacked_by_data");
    public static final ItemDefinitionComponentType STORAGE_ITEM = type("minecraft:storage_item");
    public static final ItemDefinitionComponentType STORAGE_WEIGHT_LIMIT = type("minecraft:storage_weight_limit");
    public static final ItemDefinitionComponentType STORAGE_WEIGHT_MODIFIER = type("minecraft:storage_weight_modifier");
    public static final ItemDefinitionComponentType SWING_DURATION = type("minecraft:swing_duration");
    public static final ItemDefinitionComponentType SWING_SOUNDS = type("minecraft:swing_sounds");
    public static final ItemDefinitionComponentType TAGS = type("minecraft:tags");
    public static final ItemDefinitionComponentType THROWABLE = type("minecraft:throwable");
    public static final ItemDefinitionComponentType USE_ANIMATION = type("minecraft:use_animation");
    public static final ItemDefinitionComponentType USE_MODIFIERS = type("minecraft:use_modifiers");
    public static final ItemDefinitionComponentType WEARABLE = type("minecraft:wearable");

    /**
     * Returns a built-in item-definition component type.
     *
     * @param id component identifier
     * @return matching component type, if present
     */
    public static Optional<ItemDefinitionComponentType> get(Identifier id) {
        return TYPES.get(id);
    }

    /**
     * Returns all built-in item-definition component types.
     *
     * @return component types in declaration order
     */
    public static List<ItemDefinitionComponentType> values() {
        return TYPES.values();
    }

    private static ItemDefinitionComponentType type(String id) {
        return TYPES.register(ItemDefinitionComponentType.builtIn(Identifier.parse(id)));
    }
}
