dependencies {
    api(libs.slf4j.api)
    api(libs.jackson.core)
    api(libs.jackson.annotations)
    api(libs.jackson.databind)
    api(libs.jackson.dataformat.yaml)
    api(libs.jackson.dataformat.properties)
    api(libs.completable.futures)
    api(libs.math.immutable)
    api(libs.guice)
    api(libs.guava)
    api(libs.asm)
    api(libs.asm.commons)
    api(libs.jakarta.inject)
}
